### ISSUE TITLE
v1.2.34 is incompatible with older Android API versions 

### ISSUE THREAD

**Issue by umair-ably** [ably/ably-java#1004]
The issue is related to `getOrDefault` method call which looks like was added in the 1.2.34 ably-java release specifically the Feature/no connection serial in ably-java https://github.com/ably/ably-java/pull/983/files.

It looks like `getOrDefault` needs API level 24 (android 7). Seems this method is supported in java 1.8 onwards. so older version of android using older JRE will not be able to find it.  We should explicitly mention minimum JDK/JRE version required for the ably-java project in both .gradle and README file.

They can either add android support library ( used for backward compatibility to support older APIs ) or we can revert the change from our side.

Quick fix: https://developer.android.com/studio/write/java8-support#library-desugaring

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4793) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
Link to internal conversation -> https://ably-real-time.slack.com/archives/CURL4U2FP/p1715071220126439
