### ISSUE TITLE
EventEmitter interface

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#11]
Expose an `EventEmitter` like interface in the Java library to make it more consistent with the other client libraries.  This would apply to the `Connection` and `Channel` objects.

Pseudo code example.

```java
public class ConnectionStateChangeFilter extends ConnectionStateChange {
  public Connection.ConnectionState stateFilter;
  public ConnectionStateListener;

  public ConnectionStateChangeFilter(Connection.ConnectionState state, listener ConnectionStateListener) {
    this.stateFilter = state;
    this.listener = listener;
  }

  public ConnectionStateChangeFilter(listener ConnectionStateListener) {
    this.listener = listener;
  }

  public void onConnectionStateChanged(ConnectionStateListener.ConnectionStateChange state) {
    if ( (this.stateFilter == null) || (this.stateFilter == state.current) ) {
      super(ConnectionStateListener.ConnectionStateChange state);
    }
  }
}

public void on(Connection.ConnectionState state, ConnectionStateListener listener) {
  this.listeners.add(new ConnectionStateChangeFilter(state, listener));
}

public void on(ConnectionStateListener listener) {
  this.listeners.add(listener);
}
```

**Comment by paddybyers** [comment]
This?

https://github.com/ably/ably-java/commit/dbd958a8047bd5441ae50feece4a7b572e8a0fe8

**Comment by mattheworiordan** [comment]
Sure, looks great, can we have the once method too as its used in Ruby and JS and I think is very handy, and some test coverage? Thanks

**Comment by paddybyers** [comment]
> can we have the once method too

https://github.com/ably/ably-java/commit/e3a62ac

> some test coverage

https://github.com/ably/ably-java/commit/e46e953

**Comment by mattheworiordan** [comment]
Thanks, https://github.com/ably/ably-java/compare/d0bf20eb1ee9...39f3f0226bd9
