### ISSUE TITLE
Library doesn't seem to serialise Map objects properly

### ISSUE THREAD

**Issue by stannedelchev** [ably/ably-java#112]
I'm using the following code to send a presence update:

    Map<String,Boolean> payload = new HashMap<>();
    payload.put("isTyping",false);
    try {
        sessionChannel.presence.update(payload,null);
    } catch (AblyException e) {
        e.printStackTrace();
    }

This translates to the following MsgPack hex:
`89A6616374696F6E0EA26964AD4D3754536F6A4A5A35532D3331A5636F756E7415A76368616E6E656CAB6D6F62696C653A63686174AD6368616E6E656C53657269616CB0396335333838303037353736313A3733AC636F6E6E656374696F6E4964AA4D3754536F6A4A5A3553B0636F6E6E656374696F6E53657269616C2CA974696D657374616D70CF000001533354B1D2A870726573656E63659184A8636C69656E744964A573616E6479AC636F6E6E656374696F6E4964AA4D3754536F6A4A5A3553A6616374696F6E04A464617461B07B6973547970696E673D66616C73657D`

Which translates to:
`{"action":14,"id":"M7TSojJZ5S-31","count":21,"channel":"mobile:chat","channelSerial":"9c53880075761:73","connectionId":"M7TSojJZ5S","connectionSerial":44,"timestamp":null,"presence":[{"clientId":"sandy","connectionId":"M7TSojJZ5S","action":4,"data":"{isTyping=false}"}]}
`.

However, when ably.js does a similar thing (I'm testing via the Heroku app), the MsgPack hex is:

`89A6616374696F6E0EA26964AD6E554158777A664E33522D3232A5636F756E7412A76368616E6E656CAB6D6F62696C653A63686174AD6368616E6E656C53657269616CB0396335333838303037353736313A3737AC636F6E6E656374696F6E4964AA6E554158777A664E3352B0636F6E6E656374696F6E53657269616C30A974696D657374616D70CF000001533359AAE1A870726573656E63659185A8636C69656E744964A27363AC636F6E6E656374696F6E4964AA6E554158777A664E3352A6616374696F6E04A8656E636F64696E67A46A736F6EA464617461B27B226973547970696E67223A66616C73657D`

Which translates to:
`{"action":14,"id":"nUAXwzfN3R-22","count":18,"channel":"mobile:chat","channelSerial":"9c53880075761:77","connectionId":"nUAXwzfN3R","connectionSerial":48,"timestamp":null,"presence":[{"clientId":"sc","connectionId":"nUAXwzfN3R","action":4,"encoding":"json","data":"{\"isTyping\":false}"}]}
`

The Java lib doesn't seem to create a valid JSON (IIRC JSON doesn't contain equals signs), that the JS lib can successfully parse. I set breakpoints in the JS presence handler and they do not trigger.
As a consequence of these differences, the Cordova sample app does not recognise presence messages sent from the Android sample app. 
The inverse is true - the Android lib successfully parses and displays "isTyping" presence updates coming from JS.

@mattheworiordan @paddybyers @gokhanbarisaker

**Comment by mattheworiordan** [comment]
Thanks @stannedelchev we'll get Gokhan to look at this shortly.

@SimonWoolf this reconfirms our fear that some libraries are not as interoperable as we expect.  The related issue is https://github.com/ably/wiki/issues/22, we should consider prioritising this.  

@gokhanbarisaker in the mean time, can you try and figure out why the Hashmap is being encoded as `{isTyping=false}` please and provide a fix?

**Comment by paddybyers** [comment]
> in the mean time, can you try and figure out why the Hashmap is being encoded as {isTyping=false} please and provide a fix?

The problem is that `Message.encode()` doesn't notice that the given `data` isn't JSON-serialisable:

https://github.com/ably/ably-java/blob/master/lib/src/main/java/io/ably/lib/types/BaseMessage.java#L108

If the given `data` doesn't match any of the conditions there: ie `instanceof JSONElement`, `instanceof byte[]`, instanceof `String`, then (according to `(RSL4a)`) if should throw an exception indicating that it's an invalid data type.

The demo app should either present the data in a way that allows the library to JSON-encode it, or it should present a string and do the encode/decode itself.

> this reconfirms our fear that some libraries are not as interoperable as we expect

Yes, but this case is simply a deviation from the spec, not a difference in encoding that we would only detect by testing different libraries back-to-back.

**Comment by SimonWoolf** [comment]
So I'm very far from being a java dev, but gson can apparently serialise a HashMap into json [just fine](http://stackoverflow.com/a/12156646). Why not just call `gson.toJson` on anything we get that isn't a `byte[]` or a `String`, wrap it a try-catch, and let gson throw an exception if it's fed something it can't serialize?

**Comment by paddybyers** [comment]
> Why not just call gson.toJson on anything we get that isn't a byte[] or a String

That's possible but that same approach doesn't work when deserialising - we would have to pick something canonical to deserialise to, and the end result would not be the same as the original value.

I think it is more useful on the decode side to allow clients to define their own Gson-serialisable types, and have a way for them to decode specifically to that type, instead of to a generic collection.

**Comment by stannedelchev** [comment]
So I tried using a JSONObject like this:

    JSONObject payload = new JSONObject();
    payload.put("isTyping", false);

That generates a proper JSON as the data: `{"action":14,"id":"zu4ekVHDa6-6","count":21,"channel":"mobile:chat","channelSerial":"e478831912432:13","connectionId":"zu4ekVHDa6","connectionSerial":11,"timestamp":null,"presence":[{"clientId":"sa1","connectionId":"zu4ekVHDa6","action":4,"data":"{\"isTyping\":false}"}]}`

However, my JS presence handler sees the data as a string, instead of an object :/
I noticed that the JS lib sends an additional `"encoding":"json"`member in the presence message, but it's not present in the message that the Java lib sends. 
Is this behavior OK?

**Comment by gokhanbarisaker** [comment]
@stannedelchev [this](https://github.com/ably/ably-java/blob/bcde67a28a3b9a5547ac1763e78fa7c54ff88981/lib/src/main/java/io/ably/lib/types/BaseMessage.java#L218) is the root of your problem. We are packing Java `Object.toString()` representation to data field, when we have a subclass of java object. As @paddybyers pointed out, we are only properly serialising JSONObject instances to JSON serialised String. For now, using JSONObject is the safest way to use with our library.

@paddybyers, would you like me to update public method signature to accept only JSONObject as a data argument?

**Comment by paddybyers** [comment]
No.

The library supports raw `data` - which is either a `String` or `byte[]`. This is simply passed unchanged into the structure that gets packed.

The library also supports JSON-encoding of complex types, if it recognises that they can be JSON--encoded. The current implementation requires that these are instances of `JSONElement`, meaning that they are encodable using the gson library: then it encodes the value to the JSON text and also sets the `encoding` member of the message to indicate that it is JSON (and must therefore be decoded by the client).

In the current implementation, if the `data` is not either a `String` or `byte[]` or `JSONElement` then it is coerced to a `String` (in the line linked above) and sent **as a String** to other clients. The `encoding` member is not set, and so it is not decoded by any recipient, and so it is delivered as a `String`.

So @gokhanbarisaker is is definitely not valid to limit `data` to just a `JSONObject`. The correct behaviour, as I indicated above, is not to coerce values to `String` but to reject them if they are not either a `String`, or `byte[]` or are naturally JSON-encodable.

And @stannedelchev the demo needs to pass an object that the library will JSON-encode explicitly, not just implicitly coerce to a `String`.

**Comment by mattheworiordan** [comment]
@paddybyers to avoid this unexpected co-erced string behaviour, I definitely vote we reject them. @gokhanbarisaker can you prioritise getting that to work and issue a PR for this?

**Comment by stannedelchev** [comment]
OK, I got the presence updates working.
In my last comment I was using Android's native [org.json.JSONObject](http://developer.android.com/reference/org/json/JSONObject.html) which gets coerced to string as the library checks against `com.google.gson.JsonObject`.
Once I switched over to using GSON's Json objects everything started working fine.

**Comment by mattheworiordan** [comment]
Ok, that's good @stannedelchev. It would be good to prevent other developers from hitting this snag @gokhanbarisaker if you can help

**Comment by tcard** [comment]
Just bumping this as a user just had problems with this. Maybe this should be prioritized? See ably/wiki#22.

**Comment by paddybyers** [comment]
@tcard I'm not sure what there is to fix other than a documentation issue? I don't think the java lib should be supporting all available JSON libraries; we picked one (GSON). So if you want to pass `data` values to the library and you want it serialised as JSON, your `data` must implement the relevant interface (eg `com.google.gson.JsonObject`).

**Comment by tcard** [comment]
@paddybyers This, at least:

> The correct behaviour, as I indicated above, is not to coerce values to String but to reject them if they are not either a String, or byte[] or are naturally JSON-encodable.

**Comment by paddybyers** [comment]
@tcard ok, agreed

**Comment by mattheworiordan** [comment]
@tcard can you help ensure that we reject invalid objects that don't match the expected type then?

**Comment by tcard** [comment]
@mattheworiordan Yep, I'll give it a try.
