### ISSUE TITLE
Token expiry causes alternative host names to be used

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#14]
If I have read the code correctly, when a request is made to the default end point of `rest.ably.io` and a status code outside of 200-299 is returned, then a fallback host is used to make that request again.

However, if a token has expired (code 40140), that too will trigger it to reissue the request to a fallback host, when what should happen is the token should be reissued if possible or it should fail immediately as retrying with fallback hosts is pointless.

See https://github.com/ably/ably-ruby/blob/master/lib/ably/rest/client.rb#L334-L347 in the Ruby library.

Have I misread it?

**Comment by mattheworiordan** [comment]
In fact, we should probably review which codes at https://github.com/ably/ably-common/blob/master/protocol/errors.json should trigger a retry.  Lots of them such as credential failures, invalid body, max message size exceeded etc. don't need to retry IMHO.

**Comment by paddybyers** [comment]
> Have I misread it?

I think so.

The fallback hosts are used if a `HostFailedException` is thrown, which only occurs when the problem was a `ConnectException`, `UnknownHostException`, or `NoRouteToHostException`.

**Comment by mattheworiordan** [comment]
@paddybyers but if the server responds with a 500 error code shouldn't we be using the fallback hosts?  For example, if the load balancers are unable to service a request, the client will get a response in the 5xx range.

**Comment by paddybyers** [comment]
> if the server responds with a 500 error code shouldn't we be using the fallback hosts?

The fallback hosts are only for the case that the server is unreachable. By definition, if we get any error code from the server, then it's the correct host to use.

**Comment by mattheworiordan** [comment]
I disagree.  The fallback hosts are to route around network issues or a faulty or overloaded data centre.  If a data centre becomes unhealthy for any reason, but the load balancers are still operating, all clients will continue to use the faulty data centre.  We don't want this.

**Comment by mattheworiordan** [comment]
Part of our USP is our global presence and distributed architecture.  The client libraries should automatically distribute load and move traffic to other working data centres when a single data centre for whatever reason is unable to cope with the current load.

**Comment by mattheworiordan** [comment]
@kouno and I discussed and think that the following strategy would be sensible:

* If a request fails because of network errors (see https://github.com/ably/ably-java/blob/0275671edd98e7090181696ed6dd34a01cbbd96f/src/io/ably/http/Http.java#L327), then we fallback immediately as we do
* If a request fails because of a 5xx type error, then we retry one more time, and then fallback.

This could apply to both REST & Realtime.
