### ISSUE TITLE
Prep for 0.9 spec

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#145]
@paddybyers, we need you to please with some urgency do:

* [ ] Given the severity of https://github.com/ably/ably-java/issues/133, can we please have a hot fix for this ASAP and we'll bump the version and release?
* [ ] Rebase your Android CI work and write a brief for one of the Android devs to finish this work off. Please bear in mind that https://github.com/ably/ably-java/pull/128 and https://github.com/ably/ably-java/pull/125 is part of that work

**Comment by paddybyers** [comment]
> Please bear in mind that #128 and #125 is part of that work

We will keep https://github.com/ably/ably-java/pull/125 separate for now. I want the project structure changes implemented with no other functionality changes, and then the other stuff becomes a lot less complicated.

**Comment by paddybyers** [comment]
Closing
