### ISSUE TITLE
README to include code examples and follow common format

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#15]
See https://github.com/ably/ably-ruby/blob/master/README.md for an example of a common format used for the client library README.  The README must include examples of using the most common features.  

We must also include:

* Installation instructions including how to install from a package manager i.e. similar to NPM or RubyGems
* License info
* Remove the note about being under active development
* Build status

**Comment by mattheworiordan** [comment]
We also need a very simple example of how to use the library with Android, customers have asked for this.

**Comment by mattheworiordan** [comment]
This is becoming increasingly important unfortunately...

**Comment by AdityaShirole** [comment]
The history api's usage with java library needs some code samples. The rest of the documentation is pretty good and easy to follow.

**Comment by mattheworiordan** [comment]
Thanks for the feedback @AdityaShirole, I am updating our primary docs now, so hopefully I can include a good set of examples there very soon.

**Comment by mattheworiordan** [comment]
The README states the Java lib is REST only, whereas it's clearly Realtime & REST.  It should be updated.  @JaysonMinard on twitter has pointed this out.

**Comment by mattheworiordan** [comment]
We should use the Apache license

**Comment by mattheworiordan** [comment]
@paddybyers this is quite high priority given we want people to soon start using all of our client libs, and therefore need to ensure we have consistent examples in our Github repos and code in all our examples. Is this something you can do, or can we discuss how best to tackle this?
