### ISSUE TITLE
Test failing on Travis (JDK7, JDK8, Android)

### ISSUE THREAD

**Issue by dsvishchov** [ably/ably-java#159]
As per discussion with @mattheworiordan adding this ticket for further investigation of various fails of tests on Travis (and sometimes locally) for all 3 environments (JDK7, JDK8, Android).

Out latest fixes for JDK7, JDK8 available in a separate branch:
https://github.com/ably/ably-java/tree/fix-tests

And associated latest Travis build:
https://travis-ci.org/ably/ably-java/builds/159298940

The only one thing we actually did is added delays before checking test results (in a way we already found in other tests already written) and most of issues gone, but:

1) there are still some tests which fail from time to time (which I think we need to discuss here once happens);
2) now it runs properly on JDK7, and stuck for 10 mins on JDK8 (and Travis ends job due to that), there two things to think about: a) from my point of view all test should be written in a way they don't stuck forever but rather fail with timeout exception; b) why it runs on JDK7 properly and fails on JDK8 (just to understand the nature of failing);
3) why do they run properly in most cases when ran locally?

We might definitely dive deeper into details but since you have more knowledge and experience in how library works and how tests were written it should be much more efficient if you can review and investigate.

Btw, latest Jenkins build succeeded:

> Jenkins build is back to normal : ably-java #239
> See https://ci.ably.io/job/ably-java/239/

Out latest fixes to make Android tests run (both core tests and an example of Android specific test) available in a separate branch:
https://github.com/ably/ably-java/commits/project-struct-update

And associated latest Travis build:
https://travis-ci.org/ably/ably-java/builds/159307979 

We didn't merge changes we did for regular Java tests, and also temporarily added @Ignore to one test which suspended tests execution. 

Couple of things to discuss/investigate:

1) currently it runs tests twice (> Starting 595 tests on test(AVD) - 5.1), this needs to be fixed;
2) there are still around 30 tests which are failing and require to be either fixed or removed from the execution list for Android (see Travis logs for more details).

And finally... There is still magic happens since some tests fail from time to time and even the ones we added delays for mostly ran properly (for example in the latest Travis build for Android which also runs regular tests) but sometimes failed.

**Comment by mattheworiordan** [comment]
Thanks @dsvishchov. I am not sure I can specifically comment on these points, however my view is that:

* If we identify intermittent failures we should perhaps not let this work being merged in and instead we should add separate tasks to investigate in more details.  Are we sure if we run that single test multiple times locally it does not fail for example?  If not, then we should add issues to fix the problem in due course, but get this merged in so that we don't end up with too many conflicts which is painful.
* If we have intermittent failures, can we not have a rerun strategy for those tests which tries again and logs the failure so that we can review those intermittent tests but without it blocking builds?

**Comment by mattheworiordan** [comment]
@paddybyers can you advise what we should do here?  I would like to merge in as much of the Android work as possible i.e. what's in those branches.

**Comment by mattheworiordan** [comment]
@paddybyers @trenouf is this issue as it stands still valid?

**Comment by trenouf** [comment]
@mattheworiordan  Yes, in a general way. I have a few tests that fail intermittently on java. I have not got as far as trying android yet.

**Comment by trenouf** [comment]
I am disabling the following tests:

RestAppStatsTest.appstats_day0
RestAppStatsTest.appstats_month0
RestPresenceTest.rest_presencehistory_order_text_b
RestPresenceTest.rest_presencehistory_order_text_f
RestPresenceTest.rest_presencehistory_paginate_text_b
RestPresenceTest.rest_presencehistory_paginate_text_f
RestPresenceTest.rest_presencehistory_limit_text_b
RestPresenceTest.rest_presencehistory_limit_text_f
RealtimePresenceTest.attach_enter_multiple

**Comment by trenouf** [comment]
Disabled some more tests on PR https://github.com/ably/ably-java/pull/194:
RestAppStats:
appstats_hour0
appstats_pagination0
appstats_pagination1
appstats_pagination2
appstats_pagination3

I will look at why they're failing soon.

**Comment by trenouf** [comment]
The auth tests only fail if some other tests run before them. Are all tests in a test run sharing the same app? Would that cause this problem?

**Comment by paddybyers** [comment]
> The auth tests only fail

auth?

> Are all tests in a test run sharing the same app?

Yes. The test setup does a `POST /apps` on realtime, which creates an app, and all tests are run using that.

> Would that cause this problem?

We try to avoid that in every way we can, eg with unique channel names for each test. However, stats are inevitably common, and the stats tests ought to take account of possible conflicts by limiting the values queried via start and end params, so as to be unaltered by what's happening currently.

**Comment by trenouf** [comment]
Sorry, I meant the appstats tests.

Would having a new app for each test class be too expensive?

Sounds like it would be easier to make the stats tests reliable if I just give that class its own app.

**Comment by paddybyers** [comment]
> Would having a new app for each test class be too expensive?
> Sounds like it would be easier to make the stats tests reliable if I just give that class its own app.

That would be possible but, looking at the tests, it looks like it would also be possible to prevent them from interfering by posting the stats for a minute/hour/day other than the present one.

If that's going to get too messy then we can create another app, but I believe the other libs are able to do it with a single app.

**Comment by trenouf** [comment]
OK, I'll try doing it for a day in the future or something.

**Comment by trenouf** [comment]
A year in the future seems to work. I guess it needs to be more than a month, as some of the tests are doing a month range.

**Comment by paddybyers** [comment]
I was thinking in the past :) In the future is potentially prone to getting overwritten, and it complicates the cleanup of stale data.

**Comment by trenouf** [comment]
The presence tests: the failures all seem to be where it expects channel presence history to be in forward order if direction=forwards or backward order if direction=backwards, but what it is seeing is the exact opposite. Assuming this test has worked at some point in the past, could it be a change in the order in which the channels get set up when posting the app spec to the server?

**Comment by paddybyers** [comment]
But all history is on a per-channel basis, so why would the creation order between channels make a difference?

Can you capture a specific example and post the http request and response here?

**Comment by trenouf** [comment]
I don't think I fully understand what it's trying to do then. More news later.

**Comment by trenouf** [comment]
[log.txt](https://github.com/ably/ably-java/files/556781/log.txt)

@paddy This log shows:
1. A post to sandbox/apps to set up the app, with 5 channels.
2. The response, showing the channels in reverse order (which doesn't matter at this stage, but might give some insight into what has happened in the server).
3. A get to sandbox-rest/channels to get the presence history.
4. The response, which shows the channels in the same order as (2), ie reverse.

**Comment by trenouf** [comment]
I've also got RestTimeTest.time0 and RestTimeTest.time_async failing locally. I recall someone mentioning that that happens when your clock is out of sync with the server, and indeed the clock on my mac is 13s fast.

**Comment by paddybyers** [comment]
> I've also got RestTimeTest.time0 and RestTimeTest.time_async failing locally. I recall someone mentioning that that happens when your clock is out of sync with the server, and indeed the clock on my mac is 13s fast.

The tests should query the server for the time, and determine the offset between the local machine time and the server's time. Then that offset can be used to validate the `/time` responses.

The problem with that is that it's circular, if you use the `time()` API to get the time in the beginning.

So probably the simplest thing to do is to use the Http API directly to get `/time`, and use the result of that to validate the result of `time()`.

**Comment by paddybyers** [comment]
> @paddy This log shows:
> 1. A post to sandbox/apps to set up the app, with 5 channels.

OK, so your confusion is that the POST contains one message into one channel (`restpresence_notpersisted`), and 4 messages into one other channel (`persisted:restpresence_persisted`).

I will have a look at it.

**Comment by mattheworiordan** [comment]
@paddybyers @psolstice @trenouf can we close this as I believe the issues are covered elsewhere?

**Comment by paddybyers** [comment]
I still need to check that there are specific issues raised where they need to be.

**Comment by funkyboy** [comment]
Superseded by https://github.com/ably/ably-java/issues/352
