### ISSUE TITLE
Emit errors

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#16]
On the Ruby library developers can subscribe to errors on the `Connection` and `Channel` objects.  

We should add this functionality to the Java lib.

**Comment by paddybyers** [comment]
> developers can subscribe to errors

which errors?

**Comment by mattheworiordan** [comment]
Errors such as:

* Callback exception
* Message decoding error
* Protocol error
* Connection successful but included an error message

**Comment by paddybyers** [comment]
> Callback exception

We discussed this before and agreed it's not the library's job to emit an error when the client crashed in his own code.

**Comment by mattheworiordan** [comment]
Sorry, my mistakes, the `callback exception` was meant to be logged only.  Apologies.

But we definitely discussed emitting an error yet continuing to deliver the encrypted message if there was a message decoding error.  How does the Java lib deal with that?

**Comment by mattheworiordan** [comment]
I believe this was never agreed in the 0.8 spec so should probably be considered in the 0.9 spec
