### ISSUE TITLE
RSC11: Environment option

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#160]
Please can we add an environment option to the Java lib which simply prepends the environment to the full domain for rest & realtime i.e. `clientOptions.environment = 'foo'` would result in it connecting to `foo-rest.ably.io` and `foo-realtime.ably.io` respectively for REST and Realtime endpoints.

See iOS and Javascript libraries for comparable implementations.

**Comment by mattheworiordan** [comment]
This is covered by http://docs.ably.io/client-lib-development-guide/features/#RSC11

**Comment by VOstopolets** [comment]
@mattheworiordan From http://docs.ably.io/client-lib-development-guide/features/#RSC11, environment option prepends the environment to the full domain for only **REST** endpoint. For Realtime, this is covered by http://docs.ably.io/client-lib-development-guide/features/#RTC1e. So, should I implement `RTC1e` too?

**Comment by mattheworiordan** [comment]
@VOstopolets I believe you have done this?  Should I close?

**Comment by VOstopolets** [comment]
@mattheworiordan I have created PR for this task https://github.com/ably/ably-java/pull/162 (covered by `TO3k1`, `RSC11`, `RTC1e`), and it haven't approved.

**Comment by mattheworiordan** [comment]
Given there is a PR that will be merged soon I am going to close this, thanks @VOstopolets
