### ISSUE TITLE
Move java-websocket dependency to jcenter

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#161]
The current library depends on a version of java-websocket in a personal github repo, but this needs to move to a central repository.

The original author of that project stopped updating Maven central at 1.3.0, but we need 1.3.1. We can't update Maven central so we need it to be elsewhere.

I think we should upload a version to jcenter in our own name, and update the dependencies here, and in the tutorials. There is a fork here: https://github.com/ably-forks/Java-WebSocket.

**Comment by mattheworiordan** [comment]
Note once this is completed we should tag 0.8.4, then we must remember to update the tutorials to reference 0.8.4 (most of them do) but also to not have the unnecessary Java-WebSocket dependency, see https://www.ably.io/tutorials/publish-subscribe#lang-android

**Comment by mattheworiordan** [comment]
@paddybyers is this resolved?  All of our documentation and tutorials unfortunately still references this explicitly, see https://github.com/ably/docs/pull/183/commits/7a731b3a8bfe17f7c9aa9c3fb0e278534fc20f42#diff-a551a3cd350dc478774a772f537a027fR25 for example.

Given going back and changing tutorials is a schlep, it would be nice to fix this now.

FYI @psolstice

**Comment by paddybyers** [comment]
https://bintray.com/ably-io/ably/Java-WebSocket
