### ISSUE TITLE
disconnected & suspended retry timeouts missing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#168]
See [TO3l1](http://docs.ably.io/client-lib-development-guide/features/#TO3l1) (`disconnectedRetryTimeout`) and [TO3l2](http://docs.ably.io/client-lib-development-guide/features/#TO3l2) (`suspendedRetryTimeout`).

Both options are missing from `ClientOptions`.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-401) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
We have a customer who has been asking about this for a while now (see [this internal Slack thread](https://ably-real-time.slack.com/archives/C019LDWM9UH/p1637590836038000)).

**Comment by sacOO7** [comment]
This is already implemented as a part of https://github.com/ably/ably-java/issues/956
