### ISSUE TITLE
Change JCenter package name

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#171]
See https://bintray.com/ably-io/ably, none of our packages actually have the name Ably which means a search on JCenter for https://bintray.com/search?query=ably reveals nothing as it only matches package names by default.

We should change it to `ably-java`

**Comment by mattheworiordan** [comment]
@paddybyers @psolstice whilst we are looking at https://github.com/ably/ably-java/issues/161 (assuming it's not done), we should fix this as I assume this is straightforward?

**Comment by psolstice** [comment]
Also you have strange version name change. It was 0.8.3 but now it is v0.8.4 (note the "v"). Is it intentional?

**Comment by paddybyers** [comment]
> It was 0.8.3 but now it is v0.8.4 (note the "v"). Is it intentional?

Not as far as I am aware.

**Comment by mattheworiordan** [comment]
Tags are all `v*`, see https://github.com/ably/ably-java/releases.
Seems that I assume I must have used that convention mistakenly in the jFrog versions.  Ideally I'd like to get this issue resolved along with https://github.com/ably/ably-java/issues/161 and https://github.com/ably/ably-java/pull/125 and do a release, and I expect at that stage the version number will be irrelevant as the package name changes to ably-java and ably-android instead.

@paddybyers any objection to prioritising this?

**Comment by paddybyers** [comment]
> @paddybyers any objection to prioritising this?

no

**Comment by paddybyers** [comment]
The package name is now `ably-java`.

https://bintray.com/ably-io/ably/ably-java
