### ISSUE TITLE
Intermittent connect_token_expire_disconnected failure

### ISSUE THREAD

**Issue by trenouf** [ably/ably-java#183]
I sometimes get a failure on RealtimeConnectFailTest.connect_token_expire_disconnected.

The sequence of events is supposed to be:
Auth.requestToken with ttl=8000ms
Create a different AblyRealtime passing tokenDetails from the requested token
Wait for it to connect
Wait for it to disconnect due to token expiring
Wait for it to connect when it gets a new token.

The problem I see sometimes is that, when it attempts to reconnect, it thinks the old token has not expired yet so it attempts to reuse it. Then it gets a 401 token expired from the server, which causes the connection to go into failed state and it never reconnects.

I guess this is because of a discrepancy of a couple of seconds between my PC's time and the server's time, or something.

Paddy said: If the server tells the library that it’s expired, then the library really needs to take that at face value; so I would say there’s a library problem there. The client’s time should have no bearing on anything except the creation of token requests.

Reproducing this might require deliberately provoking it by modifying TokenAuth.tokenValid to always return true.

**Comment by trenouf** [comment]
I am disabling RealtimeConnectFailTest.connect_token_expire_disconnected

**Comment by paddybyers** [comment]
This is reenabled and no longer seems to be an issue.
