### ISSUE TITLE
Connection#isConnected function

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#19]
In Ruby, because we have implemented a State Event Emitter that automatically provides predicate methods for all states such as `connected?` or `suspended?`, it's quite convenient for a developer to simply check if a connection is connected before executing some code.

Given how commonly I expect people will check if the client is connected, I propose adding a simple method `Connection#isConnected` to the `Realtime.Connection` class.

Not essential clearly, but equally so easy to implement and provides a simple way for developers to do this.

@paddybyers and @kouno thoughts?

**Comment by paddybyers** [comment]
so we have `isConnecting()`, `isSuspended()`, `isFailed()` etc as well?

**Comment by mattheworiordan** [comment]
Well @paddybyers we could do if you think it's useful?

**Comment by rjeczalik** [comment]
Sorry for chiming in, but wouldn't this be inherently race-prone? The state of the connection might change between call to `isConnected()` and actual call that user wants to make.

**Comment by mattheworiordan** [comment]
@rjeczalik correct, that is possible if you are using a threaded environment, but that is no different to saying `if (client.connection.state == CONNECTED)`.

**Comment by mattheworiordan** [comment]
And @rjeczalik please do chime in ;)

**Comment by paddybyers** [comment]
> The state of the connection might change between call to isConnected() and actual call that user wants to make

````
synchronized(channel.state) {
  // I know the connection won't drop in here ....
}
````

that would be nice :)

**Comment by rjeczalik** [comment]
@mattheworiordan: yup, direct comparison is even worse; what about:

```go
ok := client.When(ably.Connected, func() { println("I'm connected") })
if ok {
	println("was connected")
}
```

Only one method.

**Comment by kouno** [comment]
> Only one method.

We already have connection listeners for that:
```
client.connection.on('connected', function(stateChange) {
  console.log('Ably is connected');
});
```

> The state of the connection might change between call to isConnected() and actual call that user wants to make.

Well technically even if we execute the code above, there is no guarantee that the connection will be up until the callback finish executing. I mean, yes, you may decide to lock the state of the connection while executing the callback... But the connection could still drop.

**Comment by mattheworiordan** [comment]
Exactly, creating a mutex on the connection state is possible, but will not do what you want.  You cannot guarantee the connection will be open once the mutex is finished, perhaps we could do this instead ;)
```
synchronized(sharePrice)  {
  whilstTheWorldIsLockedBuySharesAtThisPriceAndMakeMoney();
}
```
He he.

**Comment by mattheworiordan** [comment]
Closing this as it did not make it in the 0.8 spec, however it's quite easy to do with http://docs.ably.io/client-lib-development-guide/features/#eventemitter
