### ISSUE TITLE
Document what proguard flags needed to make lib work with proguard

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#198]
Customer reports that when they use proguard, they get `java.lang.ClassNotFoundException: io.ably.lib.transport.WebSocketTransport$Factory`.

**Comment by paddybyers** [comment]
it looks like we need to add

    -keep public class io.ably.lib.transport.WebSocketTransport

or something like that

**Comment by trenouf** [comment]
The android build stuff is now merged into master, and I don't see any such proguard rule in there, and I believe I ran the tests as successfully as on JRE.

**Comment by paddybyers** [comment]
I assume it applies when an app includes the library and they then specify some minimisation/obfuscation for the app.

**Comment by akoul889** [comment]
We tried using this `-keep public interface io.ably.lib.transport.WebSocketTransport$Factory {*;}`
to fix this issue as described  [here](http://stackoverflow.com/a/25711830)

But using this fixed the problem
`-keep class io.ably.lib.** { *; }
-keep class org.msgpack.core.** { *; }`

Don't know where `org.msgpack.core` is coming from. Couldn't find that in the sdk.

**Comment by paddybyers** [comment]
The readme has been updated, but also see https://github.com/ably/ably-java/issues/223
