### ISSUE TITLE
Host ClientOptions

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#22]
We currently use `host` and `wsHost` in ClientOptions, could this be `restHost` and `realtimeHost` for consistency and to remove ambiguity of what `host` is for?

**Comment by paddybyers** [comment]
Strictly though the `wsHost` is for realtime websocket connections and `host` is for realtime comet connections (as well as REST).

**Comment by mattheworiordan** [comment]
@paddybyers well `host` and `wsHost` in my mind that is even more confusing then and we need a name change!

**Comment by mattheworiordan** [comment]
@paddybyers we need to decide on this.  PHP lib currently uses `host` and I've asked to change to `restHost`.  In the case of PHP, having `restHost` seems odd given it's only a REST lib.  I'm not even sure this needs to be a documented option to be honest, can we discuss?

**Comment by paddybyers** [comment]
This is resolved.
