### ISSUE TITLE
Timeout in test suite

### ISSUE THREAD

**Issue by kouno** [ably/ably-java#24]
It looks like the java test suite tends to timeout on Travis.

https://travis-ci.org/ably/ably-java/builds/61492791
https://travis-ci.org/ably/ably-java/builds/61596086

On our CI, I could not reproduce it by running the test suite alone. I had to run the travis tests at the same time to see it happen again.

**Comment by paddybyers** [comment]
These builds both failed at more or less the same point, and it's running tests that attempt to send 1000 messages, one every millisecond. I suspect that this is loading the travis resource in a way that it doesn't like. Or maybe there is a bug that causes the tests to fail when run on an underresourced machine.

**Comment by kouno** [comment]
It also happens on our CI machine when a Travis builds is running. Which eliminate the under-resourced machine hypothesis.

**Comment by paddybyers** [comment]
> Which eliminate the under-resourced machine hypothesis

I think that failure you linked is different.

**Comment by kouno** [comment]
What makes you think that they are not linked?

**Comment by paddybyers** [comment]
It's failed this time in this test : `recover_implicit_connect`

> What makes you think that they are not linked?

I thought that travis specifically having an issue with those high-rate message tests was potentially an issue.

This issue on CI - it's potentially the same but I'm betting otherwise :)
