### ISSUE TITLE
0.9 spec: UPDATE event, replacing ERROR

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#244]
https://github.com/ably/docs/pull/208/files

New spec is designed to be more straightforward for typed languages to implement than the old, which ably-java never fully implemented anyway (e.g. all events emitted by the Connection now have the interface (with a ConnectionStateChange as the first arg), and likewise for Channel)

**Comment by mattheworiordan** [comment]
@paddybyers this is implemented, can I close?

**Comment by paddybyers** [comment]
Closing
