### ISSUE TITLE
authParams & authMethod ClientOptions

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#25]
In the Ruby lib, when using `authUrl`, `authParams` when configured will send query params if using `GET`, and will send post data when using `POST`.

There is an additional `authMethod` option that allows the verb to be set.

See `auth_` options at http://www.rubydoc.info/gems/ably/0.8.1/Ably/Realtime

I would prefer that the developer has explicit control over which verb is used as is done with the Ruby library.  WDYT?

**Comment by paddybyers** [comment]
... with the supported methods only being `POST` and `GET` ?

**Comment by mattheworiordan** [comment]
@paddybyers that is all I have supported in Ruby, but we could very easily add more

**Comment by paddybyers** [comment]
I'm not asking for more, just checking.

**Comment by mattheworiordan** [comment]
OK, what do you think?

**Comment by paddybyers** [comment]
Supporting `GET` and `POST` only is fine for now and we can add others if really necessary.

**Comment by paddybyers** [comment]
Closing; this was implemented in https://github.com/ably/ably-java/pull/340
