### ISSUE TITLE
Java logLevel

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#26]
Shouldn't the log level be at least errors by default?

See https://github.com/ably/ably-java/blob/db50628fceb0af37c63c33693ab77dbb35d3c245/src/io/ably/util/Log.java#L132

**Comment by sanjuthomas** [comment]
Do you have any plan to convert this project into a maven project? may be I can help you guys with maven and log4j integration if you like.

**Comment by paddybyers** [comment]
> Do you have any plan to convert this project into a maven project?

Yes.

> log4j integration

I was thinking we would use SLF4J because I would prefer to avoid log4j as a dependency for Android in particular. What would you recommend?

**Comment by mattheworiordan** [comment]
@sanjuthomas sure, we would certainly be happy if you were able to help.  What do you propose?

**Comment by sanjuthomas** [comment]
Thanks; I can first cover this project into maven project. Then upgrade the logging framework once we have consensus on the logging framework.

**Comment by sanjuthomas** [comment]
I tried to mavenise the project today. I got every dependencies except the  org.msgpack. I used the following versions but two class didn't compile with those versions.
		<dependency>
			<groupId>org.msgpack</groupId>
			<artifactId>msgpack</artifactId>
			<version>0.6.12</version>
		</dependency>

Classes didn't compile are 1. BaseMessage and 2.WebSocketTransport

1.  org.msgpack.type.ValueType.BIN is missing in the version that I picked. 
2.  One of your classes WsClient (inner class in WebSocketTransport) is missing a method name setSocket.

Can anyone help here?

**Comment by petergphillips** [comment]
I ran into the same issue today with the dependencies whilst trying to build a proper ably jar (not a fat one).  It appeared to me that both msgpack and java-websocket had been modified and re-built by ably from the original versions.

I think that these would then need to be published separately by ably and moved to their own io.ably package structure, or alternatively merge requests raised with the original authors to get the changes incorporated.

In the meantime the choice in the pom.xml is either to upload the artifacts to your local maven repository or use a maven system dependency.

**Comment by paddybyers** [comment]
@petergphillips yes, you're right. We're about to release a new version which resolves these problems (see https://github.com/ably/ably-java/tree/gson).

The msgpack dependency has been updated (there was a complete API change between the version we were using and the latest), and the java-websocket depedency (for which the latest version wasn't on Maven central) is obtained from a github repo. (The java websocket change we made was simply to subset the jar to contain only the client classes and not the server classes - we might still make that change but it would be a separately published configuration.)

**Comment by mattheworiordan** [comment]
@paddybyers what is the status on this?

**Comment by paddybyers** [comment]
The default log level is updated to `WARN`:

https://github.com/ably/ably-java/commit/634f8dac4c1a9473d19c6267c1c11447a7dba8a6

The migration to use SL4J has not been attempted yet.

The other issues discussed above with dependencies are resolved.

I think this issue should be closed and a separate issue raised, if we want to, to address future migration to use SL4J.
