### ISSUE TITLE
Add support for ConnectionDetails.connectionStateTtl

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#267]
We keep getting the log message telling us that it's an unknown field.

**Comment by mattheworiordan** [comment]
@paddybyers should we not as part of this fix ensure any unknown fields are ignored so that future changes don't introduce problems like this again?

**Comment by paddybyers** [comment]
> should we not as part of this fix ensure any unknown fields are ignored so that future changes don't introduce problems like this again?

All unrecognised fields are safely ignored already, except for emitting a log message. We can downgrade the log message or remove it altogether.

**Comment by mattheworiordan** [comment]
This is resolved
