### ISSUE TITLE
autoConnect & useTokenAuth

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#27]
See the corresponding options in http://www.rubydoc.info/gems/ably/0.8.2/Ably/Realtime
- autoConnect can be used to disable the client lib connecting requiring an explicit connect
- useTokenAuth forces the client library to authenticate with tokenAuth

We should add these options for consistency across all client libs

**Comment by mattheworiordan** [comment]
Related to https://github.com/ably/ably-js/issues/70

**Comment by paddybyers** [comment]
These are implemented; closing
