### ISSUE TITLE
Maven / Ivy support

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#28]
Comment from @jasyonminard on Twitter:

> @ablyrealtime Lastly, in Java is normal to publish a Maven/Ivy artifact.

We should consider adding Maven and Ivy support.

**Comment by sanjuthomas** [comment]
I am working on maven support. will send a pull request in couple of days.

**Comment by paddybyers** [comment]
I'm looking now at what's the best way to support Android developers using Studio. Should we be using Maven/Ivy or gradle?

**Comment by mattheworiordan** [comment]
We have agreed we will publish to JCenter instead as this is the new defacto standard.

**Comment by mattheworiordan** [comment]
@paddybyers can we close this now that `gradle` support is merged in?

**Comment by paddybyers** [comment]
> can we close this now that gradle support is merged in?

we should upload artifacts to jcenter and then we can close it

**Comment by mattheworiordan** [comment]
FYI, we now have an account with https://bintray.com which we should use to publish binaries.

**Comment by paddybyers** [comment]
https://bintray.com/ably-io/ably/ably-java
