### ISSUE TITLE
Redis message keys leaked

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#282]
We seem to be leaking message keys in redis. For example, on peoplefun instance `i-033b2b01b7cb83a7d` each redis keyspace contains about 10 million `epoch*` keys

**Comment by tcard** [comment]
This isn't meant for ably-java, is it?

**Comment by mattheworiordan** [comment]
Issue moved to [ably/realtime #826](https://github.com/ably/realtime/issues/826) via [**ZenHub**](https://www.zenhub.com/)
