### ISSUE TITLE
0.8.10  bug during dex translation

### ISSUE THREAD

**Issue by ousenko** [ably/ably-java#288]
Hello, after upgrade from 0.8.4 to 0.8.10 I see:

```
>:app:transformClassesWithDexForStageDebug
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lio/ably/lib/BuildConfig;
1 error; aborting
```

App is multidex. 

`compile "io.ably:ably-java:0.8.10"` used, from `jcenter()` I suppose

What are we to do about it? Exclude this BuildConfig ? Is it safe for ably lib operation ?

NOTE: I see that internals of BuildConfig are different between 0.8.4 and 0.8.10, if this means something

**Comment by mattheworiordan** [comment]
Hi @ousenko. Sorry to hear that, I'll get one of our Java devs to advise shortly.

**Comment by paddybyers** [comment]
We resolved a name conflict in this commit: https://github.com/ably/ably-java/commit/ca6f43305cbcbf098fa92f3b10f9535ef28c90d7#diff-9d225bc39d80f8e6874619bca156dfc7

which changes the name of one of the two versions of `BuildConfig`. That change was introduced in 0.8.6.

It is possible that the problem will be resolved with a `gradle clean` - I suspect you have an artifact from earlier builds that still contain the binary for the renamed class.

**Comment by paddybyers** [comment]
I can confirm that there was an issue with the `ably-java` binary on bintray. That is now resolved and a new version is uploaded. Sorry for the inconvenience.

You will need to clean the old version from your gradle cache.

Having said that, is this an Android project or a JRE project? Perhaps you need to be using the Android version:

    compile "io.ably:ably-android:0.8.10"

The `BuildConfig` problem was not present on the Android release, on the java release.

**Comment by paddybyers** [comment]
> You will need to clean the old version from your gradle cache.

We're going to do a 0.8.11 release which is identical, except for the packaging issue that led to this problem on the java release. By referring to that you can avoid the step of clearing the gradle cache. I will post here once that is released.

However, in the meantime, the newest 0.8.10 binaries on Bintray are fine, and if you use the Android release then there won't be a problem anyway.

**Comment by paddybyers** [comment]
> We're going to do a 0.8.11 release ... I will post here once that is released.

Done: https://bintray.com/ably-io/ably/ably-java/0.8.11
