### ISSUE TITLE
Proposal: errorReason instead of reason

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#30]
In the [client lib spec](http://docs.ably.io/client-lib-development-guide/features/), I have opted for errorReason as the attribute of a connection as opposed to simply @reason@.  I have also done the same for the @ConnectionStateChange@ object as I think it is clearer, see https://github.com/ably/docs/commit/e114527d55f15c8a4d5e8cae48351372c3babb7b.

I propose we use errorReason instead of reason in all client libs, can we make this change if you agree?

**Comment by mattheworiordan** [comment]
BTW. I appreciate the naming could be useful without error in it so that if we wanted to include a success reason we could do that, however the attribute is an @ErrorInfo@ type so it's always going to contain an error type currently anyway.

**Comment by paddybyers** [comment]
I'm in two minds about this.

The `ConnectionStateChange` is indicating a state change, and `reason` is therefore clearly the reason for the change, even if it's not an error (eg if the connection is explicitly closed by the user).

I agree that `Connection.reason` would benefit from clarification-through-verbosity, but again, strictly, it isn't necessarily an error.

**Comment by mattheworiordan** [comment]
Mmm, OK, I assumed because reason is an [ErrorInfo type in Java](https://github.com/ably/ably-java/blob/master/src/io/ably/realtime/Connection.java#L19-L22), and is [described as an error](https://github.com/ably/ably-java/blob/master/src/io/ably/realtime/Connection.java#L19-L22), it would only be an error.  If you think there are valid reasons we need to expose `Connection#reason` when it's not an error, then arguably reason is right, but do we need to do that?

**Comment by mattheworiordan** [comment]
Any further thoughts @paddybyers?

**Comment by paddybyers** [comment]
I think:
- it's debatable whether or not `errorReason` is an improvement on what we have;
- we have more important things to do than fiddle with it.

**Comment by mattheworiordan** [comment]
Will move to 0.9 proposals that will be reviewed in due course
