### ISSUE TITLE
Add example of publishing a JsonObject to readme?

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#307]
Customer [here](https://app.intercom.io/a/apps/ua39m1ld/inbox/all/conversations/8135841515) had a Map and wanted to publish it, properly json-encoded. (It was getting published as a string). I told him that it needed to be an instance of `com.google.gson.JsonElement` (e.g. a JsonObject); he asked how to coerce a Map to a JsonObject. As a non-java dev I had no idea -- the [gson docs](https://static.javadoc.io/com.google.code.gson/gson/2.6.2/com/google/gson/JsonObject.html) don't help much (while Android's [JSONObject](https://developer.android.com/reference/org/json/JSONObject.html#JSONObject(java.util.Map))'s constructor can take a Map, Gson's JsonObject constructor can't), and I couldn't find any examples in the tests of publishing JsonObjects; the all seem to use strings. Would be nice to:

1. Specify in the Readme that objects (apart from strings or bytearrays) have to be instances of JsonElement to be encoded properly
2. Give an example of publishing a Map by coercing it to JsonObject, however that's done. Or if that's not possible, at least an example of constructing and publishing a JsonObject.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-412) by [Unito](https://www.unito.io)

**Comment by mattheworiordan** [comment]
Could we not automatically coerce popular JSON class objects?

**Comment by SimonWoolf** [comment]
> Could we not automatically coerce popular JSON class objects?

Paddy wasn't a fan of that last time this was discussed, see https://github.com/ably/ably-java/issues/112#issuecomment-190923908 - "*That's possible but that same approach doesn't work when deserialising - we would have to pick something canonical to deserialise to, and the end result would not be the same as the original value.*"

**Comment by mattheworiordan** [comment]
See https://github.com/ably/ably-dotnet/issues/92, a similar conversation in some was for .NET.  Customer wanting to use their own serialiser.  For typed languages, we may want to think about some options here, even if it's just a documented recommendation.
