### ISSUE TITLE
Crash inside a library

### ISSUE THREAD

**Issue by ousenko** [ably/ably-java#309]
With 
`compile "io.ably:ably-java:0.8.4"`

I received this crash twice:

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void io.ably.lib.transport.ITransport.send(io.ably.lib.types.ProtocolMessage)' on a null object reference
 Raw Text
io.ably.lib.transport.ConnectionManager.sendImpl (ConnectionManager.java:753)
io.ably.lib.transport.ConnectionManager.sendQueuedMessages (ConnectionManager.java:760)
io.ably.lib.transport.ConnectionManager.setState (ConnectionManager.java:201)
io.ably.lib.transport.ConnectionManager.handleStateChange (ConnectionManager.java:503)
io.ably.lib.transport.ConnectionManager.run (ConnectionManager.java:588)
java.lang.Thread.run (Thread.java:818)
```

**Comment by mattheworiordan** [comment]
Sorry to hear that @ousenko, I'll get one of the Java guys to take a look.

Are you able to provide any additional information in terms of your platform, what you think causes it, any other info that may help us debug the issue?

**Comment by mattheworiordan** [comment]
Ok, we'll investigate.

**Comment by mattheworiordan** [comment]
Hi @ousenko. We've not yet had time to focus on this I am afraid as we've all been flat out on a big upgrade due out tomorrow for the platform. We'll look at this soon after, sorry for the delay.

**Comment by SimonWoolf** [comment]
Hi @ousenko . I notice you're using 0.8.4; this is quite an old version, there have been several fixes (including to the message queue) since then. Would you mind upgrading to the latest version (1.0), and letting us know if you still have this issue?

**Comment by ousenko** [comment]
Hi @SimonWoolf sure I will surely try

**Comment by paddybyers** [comment]
If you are still able to reproduce this with 1.0 then we'll have a look.

**Comment by ousenko** [comment]
I am not able to reproduce it even on 0.8.4

This is what our users randomly reproduce in production

It might take a few weeks before we know thing is stable

**Comment by paddybyers** [comment]
OK, thanks, we do appreciate the feedback. I will continue to have a look and see if I can see a reason why that would happen.
