### ISSUE TITLE
Dependency management for ably-android

### ISSUE THREAD

**Issue by ousenko** [ably/ably-java#316]
Hi guys, this is not the first time I encounter issue with `ably-android` artifact dependency but I finally got my hands to report about this

Using your suggested approach of adding dependency into gradle buildscript like this:

```
buildscript {
    repositories {
        jcenter()        
    }
}
dependencies{
...
compile 'io.ably:ably-android:1.0.0'
...
}
```

does not work for me.

```
Failed to resolve: io.ably:ably-android:1.0.0
Failed to resolve: annotationProcessor
```

If I use `io.ably.ably-java:1.0.0` instead - works smooth.

Any reason for that? Could you reflect the changes actually needed to incorporate android version of artifact?

**Comment by paddybyers** [comment]
Apologies for that; the files were uploaded with the wrong path in the repository. It should be fixed now.
