### ISSUE TITLE
1.0.0 sending v=0.9

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#324]
Noticed in the admin api, looks like ably-java 1.0.0 is still sending `v=0.9` - https://github.com/ably/ably-java/blob/master/lib/src/main/java/io/ably/lib/transport/Defaults.java#L8

**Comment by paddybyers** [comment]
Fixed by https://github.com/ably/ably-java/commit/4e4a52f4c589e2471addbae39bcd6d054fb7fc37
