### ISSUE TITLE
PaginatedResult#isLast method missing

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#33]
See https://goo.gl/2aoKPg, and the spec `TG7` at http://docs.ably.io/client-lib-development-guide/features/, `isLast` method is missing.

**Comment by paddybyers** [comment]
I thought that last time we reviewed that spec we agreed to remove `isLast()` ?

**Comment by mattheworiordan** [comment]
Not as I recall, only `isFirst` because of the issue relating to the cursor and current not necessarily reflecting the first position.  I don't see any agreement on that.

**Comment by gokhanbarisaker** [comment]
is `!hasNext()` and `isLast()` has a difference?

**Comment by gokhanbarisaker** [comment]
Also, docs for TG7 seems confusing, where `isLast` returns true for non-last pages

> (TG7) PaginatedResult#isLast function returns true if this page is **not** the last page i.e. !hasNext

**Comment by paddybyers** [comment]
> !hasNext() and isLast() are same things, aren't they?

Yes

> docs for TG7 seems confusing

You're right, and the doc is wrong.

**Comment by mattheworiordan** [comment]
Typo in TG7 fixed at https://github.com/ably/docs/commit/08de08e7b75d21bf455f68111f0afaf3e2ba1999
