### ISSUE TITLE
Tests failing because of "no output in the last 10m"

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#330]
It seems the test suite is getting "stuck" and the test suite is failing to run in full.

I would have assumed each test would have a timer on it to prevent it becoming locked on one test.

Annoyingly, if you see the last three failing builds, none of them got stuck at the same point:

https://travis-ci.org/ably/ably-java/jobs/245301016
https://travis-ci.org/ably/ably-java/jobs/245301018
https://travis-ci.org/ably/ably-java/jobs/245301017

**Comment by mattheworiordan** [comment]
@paddybyers it would be good if we could find a plugin / attribute of Gradle that enforces a max time per test.

**Comment by paddybyers** [comment]
Timeout have been added to tests so all tests will fail with a timeout error if they do not complete in a set time: https://github.com/ably/ably-java/commit/cbb9a69559f321ff38f1eb3ac8211d1c19a6e69a

**Comment by paddybyers** [comment]
In (our internal) Jenkins CI, the CI runs are now completing with a small number of realtime failures. There are currently no tests timing out.

I will raise separate issues in respect of the test failures.

This issue can be closed once we see the tests runs complete on Travis

**Comment by funkyboy** [comment]
There seem to be no more timeouts now: https://travis-ci.org/ably/ably-java/builds/354437117
Closing.
