### ISSUE TITLE
UTF-8 / ASCII detection issue in compile

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#334]
We are seeing this in the builds in Jenkins:

```
/ably-java/lib/src/main/java/io/ably/lib/rest/Auth.java:71: error: unmappable character for encoding ASCII
     * TO3j7: authMethod ??? The HTTP verb to be used when a request
```

**Comment by paddybyers** [comment]
See https://discuss.gradle.org/t/unmappable-character-for-encoding-ascii-when-building-a-utf-8-project/10692/10

**Comment by paddybyers** [comment]
By far the simplest fix is just to remove the two instances of non-ASCII characters in the comments: https://github.com/ably/ably-java/commit/3bfdf99958ce6a1a90358ef52016380d95d4c8be
