### ISSUE TITLE
Gradle version should be upgraded

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#335]
If using a version older than `2.14`, the builds do not work.

See https://gist.github.com/mattheworiordan/28fe6da37af0bfb997cb015ff4561e38 for the log. We should consider an upgrade to the latest version.

**Comment by funkyboy** [comment]
This has been updated in https://github.com/ably/ably-java/commit/0a45ab1e855af65ab7545b4e3c58252af1413ca2 
Closing.
