### ISSUE TITLE
TokenRequest.asJson should omit TTL if default

### ISSUE THREAD

**Issue by thedavidmeister** [ably/ably-java#349]
If I call `createTokenRequest` with no additional parameters in Java and JS I get different results.

To compare the two directly I'm using `.asJson` on the Java `TokenRequest`.

The Java version has a key `ttl` that JS does not have.

The JS version has a key `capability` that Java does not have.

**Comment by paddybyers** [comment]
Well spotted :)

The spec for this is here: https://docs.ably.io/client-lib-development-guide/features/#RSA9

I think both `ttl` and `capability` should be omitted if no non-default values are specified by the caller, so both are wrong :)

**Comment by paddybyers** [comment]
@SimonWoolf wdyt?

**Comment by thedavidmeister** [comment]
yes i ended up needing to make them both optional, with a spec like this (clojure/clojurescript):

```
(spec/def :ably.rest/token-request
 (spec/keys
  :req-un [:ably.rest/keyName
           :ably.rest/timestamp
           :ably.rest/nonce
           :ably.rest/mac]
  ; https://github.com/ably/ably-java/issues/349
  :opt-un [:ably.rest/clientId
           :ably.rest/capability
           :ably.rest/ttl]))
```

**Comment by thedavidmeister** [comment]
FYI `req-un` = required and `opt-un` = optional keys

**Comment by SimonWoolf** [comment]
I agree, if not user-specified it should be omitted -- https://docs.ably.io/client-lib-development-guide/features/#RSA5 and https://docs.ably.io/client-lib-development-guide/features/#RSA6 are clear on this, see past discussion https://github.com/ably/docs/issues/245 and https://github.com/ably/docs/pull/246 .
