### ISSUE TITLE
Implement connection state freshness check

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#358]
Spec PR: https://github.com/ably/docs/pull/331/files

This is quite high priority; see https://github.com/ably/realtime/issues/1289#issuecomment-341152556 for why, or ask me or Matt in #client-libraries on slack.

See https://github.com/ably/ably-js/blob/c55b4518d6f096e4bde90afcd04c5ba35d466f3c/common/lib/transport/connectionmanager.js#L702-L712 for example implementation

**Comment by paddybyers** [comment]
Fixed by https://github.com/ably/ably-java/pull/390
