### ISSUE TITLE
Push release include problem

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#359]
After following the instructions for https://github.com/ably/ably-java/pull/308, a customer is reporting:

> i successfully added
> apply from: '/path/to/your/clone/of/ably-java/dependencies.gradle'
> but i dont find any file located at "Android" folder --> apply from: '/path/to/your/clone/of/ably-java/android/dependencies.gradle'
> Fallowed all the steps
still not able to import "not able to import "AblyRegistrationIntentService" class"

I will ask for more info.

**Comment by tcard** [comment]
The customer wasn't on the right branch.
