### ISSUE TITLE
Add (or fix) CI tests on different platforms

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-java#364]
- Java
  - SDK7
  - SDK8

- Android
  - TBD

**Comment by funkyboy** [comment]
[This is a good starting point](https://developer.android.com/about/dashboards/index.html) to have an idea of Android usage by version.

**Comment by paddybyers** [comment]
We have a dependency in the library on Java 7 language features (in particular `switch(String)` which was supported from Android-19 (4.4, KitKat) onwards). This limitation has existed for a while and we've not had customers reporting this as an issue.

This means that for development you need to be using an Android-19 or later SDK version, but the specific language feature we use doesn't prevent the generated bytecode from running on earlier versions.

The linked stats show that pre-4.4 versions account for 5.7%, and pre-4.1 (Android-16) account for 0.7%.

5.7% is probably a higher percentage than we would like to exclude.

So the answer is that we should support Android-19 onwards as a target SDK version, and Android-16 onwards as a target platform version. I think we should build with the latest widely-supported toolchain version (ie the version of gradle that ships with the current version of Android Studio), and then ideally run tests on 4.1, 4.4 and the most recent version with relatively wide adoption (which currently would be 7.1).

@funkyboy wdyt?

**Comment by funkyboy** [comment]
After a bunch of adventures with Travis I have the tests running on:
- android-22
- java8
- openjdk7

Extending tests to other android targets (`android-25` and the like) might require switching to a different Travis image (now we are using [`android`](https://github.com/ably/ably-java/blob/develop/.travis.yml#L1)). 
I propose to limit this issue to the three targets listed above. 
I [opened an issue](https://github.com/ably/ably-java/issues/373) about testing on more Android targets.
