### ISSUE TITLE
Maven devpendency failed

### ISSUE THREAD

**Issue by sajanlamsal** [ably/ably-java#383]
<dependency>
            <groupId>io.ably</groupId>
            <artifactId>ably-java</artifactId>
            <version>1.0.2</version>
            <type>pom</type>
        </dependency>

dependency not found.

**Comment by paddybyers** [comment]
Can you give any more details of the problem? Is it the ably-java module that's not found, or one of its dependencies?

Which repositories are you using? We're on jcenter (https://bintray.com/ably-io/ably/ably-java/1.0.2).

**Comment by funkyboy** [comment]
@sajanlamsal thanks for reporting this. Are you building a Java or Android project? Which IDE? Can you share some more details about the context in which this is happening?

Even a very simple project that reproduces this is fine.

**Comment by sajanlamsal** [comment]
Hello, I am using IntelliJ and it is a java project (Maven). 
[]([https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000686704-How-to-install-packages-from-JCenter-) 
I found out that, JCenter is not supported for maven in IntelliJ.

**Comment by paddybyers** [comment]
See https://youtrack.jetbrains.com/issue/IDEA-154970

Our testing in IntelliJ uses Gradle so I've not tested with maven. But isn't there a difference between setting up an IJ project with the internal build system (which doesn't support JCenter) vs setting it up as a maven project?

**Comment by funkyboy** [comment]
@sajanlamsal Closing this. Feel free to reopen if it's still an issue.
