### ISSUE TITLE
Token authentication "Request mac doesn't match"

### ISSUE THREAD

**Issue by stannedelchev** [ably/ably-java#40]
I'm trying to use the same pattern for connecting to Ably as [the one I'm using in the cordova demo app](https://github.com/ably/demo-mobile-phonegap-cordova/blob/master/www/js/app.js#L99) - providing clientId and authUrl to the Realtime instance.

    app.ably = new Ably.Realtime({
        authUrl: 'https://www.ably.io/ably-auth/token-request/demos',
        clientId: clientId,
        log: { level: 4 }
    });

However, running similar code (listing below) on Android, I'm getting a `Request mac doesn't match` error. Connecting with `clientOptions.key = "..."`, instead of `authUrl` works fine. I have enabled the INTERNET permission in AndroidManifest.xml.

```
I/System.out﹕ Sending WAIT chunk
I/System.out﹕ (INFO): io.ably.realtime.AblyRealtime: started
I/System.out﹕ (INFO): Auth(): using token auth with authUrl
I/System.out﹕ (VERBOSE): io.ably.transport.ConnectionManager: requestState(): requesting connecting; id = null
I/System.out﹕ (VERBOSE): io.ably.transport.ConnectionManager: notifyState(): notifying connecting; id = null
I/System.out﹕ (INFO): TokenAuth.authorise():
I/System.out﹕ (INFO): TokenAuth.authorise(): requesting new token
I/System.out﹕ (INFO): Auth.requestToken(): using token auth with auth_url
W/DefaultRequestDirector﹕ Authentication error: Unable to respond to any of these challenges: {}
I/System.out﹕ (ERROR): io.ably.http.Http: Error response from server: statusCode = 401; responseBody = {
I/System.out﹕ "error": {
I/System.out﹕ "statusCode": 401,
I/System.out﹕ "code": 40101,
I/System.out﹕ "message": "Request mac does not match",
I/System.out﹕ "serverId": "frontend.d00f.production-eu-central-1-A.i-12ef73d3"
I/System.out﹕ }
I/System.out﹕ }
I/System.out﹕ (ERROR): io.ably.transport.WebSocketTransport: Unexpected exception attempting connection; wsUri = wss://realtime.ably.io:443/
I/System.out﹕ io.ably.types.AblyException: Request mac does not match
I/System.out﹕ at io.ably.http.Http.handleResponse(Unknown Source)
I/System.out﹕ at io.ably.http.Http.postForHost(Unknown Source)
I/System.out﹕ at io.ably.http.Http.post(Unknown Source)
I/System.out﹕ at io.ably.rest.Auth.requestToken(Unknown Source)
I/System.out﹕ at io.ably.http.TokenAuth.authorise(Unknown Source)
I/System.out﹕ at io.ably.rest.Auth.authorise(Unknown Source)
I/System.out﹕ at io.ably.rest.Auth.getAuthParams(Unknown Source)
I/System.out﹕ at io.ably.transport.WebSocketTransport.connect(Unknown Source)
I/System.out﹕ at io.ably.transport.ConnectionManager.connectImpl(Unknown Source)
I/System.out﹕ at io.ably.transport.ConnectionManager.handleStateRequest(Unknown Source)
I/System.out﹕ at io.ably.transport.ConnectionManager.run(Unknown Source)
I/System.out﹕ (VERBOSE): io.ably.transport.ConnectionManager: notifyState(): notifying disconnected; id = null
I/System.out﹕ (VERBOSE): io.ably.transport.ConnectionManager: setState(): setting disconnected
V/ABLY CONNECTION CHANGE﹕ Request mac does not match
```

Code:

    @Override
    protected void onResume() {
        super.onResume();

        try {
            ClientOptions clientOptions = new ClientOptions();
            clientOptions.logLevel = io.ably.util.Log.VERBOSE;
            clientOptions.clientId = "stan";
            clientOptions.authUrl = "https://www.ably.io/ably-auth/token-request/demos";
            AblyRealtime realtime = new AblyRealtime(clientOptions);
            realtime.connection.on(new ConnectionStateListener() {
                @Override
                public void onConnectionStateChanged(ConnectionStateChange connectionStateChange) {
                    Log.v("ABLY CONNECTION CHANGE", connectionStateChange.reason.message);
                }
            });
        }
        catch(AblyException e) {
            e.printStackTrace();
        }
    }

**Comment by mattheworiordan** [comment]
@paddybyers can you help?

**Comment by paddybyers** [comment]
So, the underlying issue is this bug in the Android JSON library:

http://stackoverflow.com/questions/18226288/json-jsonobject-optstring-returns-string-null

We're getting `"clientId": null` back from the token request server, and this is getting resolved, essentially, as `"clientId": "null"` :(

I will push a fix.

**Comment by paddybyers** [comment]
Can you confirm that latest master fixes this for you? (Specifically https://github.com/ably/ably-java/commit/d209d3696ec4a1626ea3f6ca1a81731b53c9a669)

**Comment by stannedelchev** [comment]
Confirmed, latest `master` ( 8a11affa1272e1dd168b7dbe33595a9cd464ebf2 ) works fine.
