### ISSUE TITLE
Idempotent publishing is not enabled in the upcoming 1.1 release

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#438]
See https://github.com/ably/docs/pull/568

We must ensure that that idempotent is not yet enabled by default and requires the user to explicitly enable.

Related to #413

**Comment by paddybyers** [comment]
This is done: https://github.com/ably/ably-java/blob/b0d68c674302950ddca9548e84f87a75f213c2f5/lib/src/main/java/io/ably/lib/types/ClientOptions.java#L131
