### ISSUE TITLE
Gradle build should be able to build library without Android SDK installed

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#46]
The `android-test` project requires the Android gradle plugin and so all tasks invoked on the top-level project fail if the Android SDK is not installed.

**Comment by paddybyers** [comment]
See: https://github.com/ably/ably-java/pull/47

**Comment by mattheworiordan** [comment]
@paddybyers: assigning this ticket to you as a reminder that it would be good to merge this in plus respond / close any open PRs as I expect they are now outdated.  Also, please try and get CI passing and I will enable for Travis

**Comment by mattheworiordan** [comment]
@paddybyers merging your branches into `master` is now quite critical as people are starting to do PRs on out of date code which may conflict.  Can this be prioritised please?

**Comment by paddybyers** [comment]
> merging your branches into master is now quite critical as people are starting to do PRs on out of date code which may conflict.

`master` now has the gradle build and all tests are passing in CI.

This bug (unable to build without Android SDK installed) is also resolved, so I'm closing this issue.

**Comment by mattheworiordan** [comment]
Thanks
