### ISSUE TITLE
Presence blocking get sometimes has missing members

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#467]
From customer (see ticket https://support.ably.io/a/tickets/97899) 

> Intermittently during testing (and pretty consistently once we started detaching after a Channel.presence.get(true) blocking call returned), we saw presence incorrectly omit attached clients (i.e. presence would report no clients connected, but our subsequent messages on the channel were successfully delivered). The issue was not observed during debugging, suggesting a race condition. While I expect we could get around this issue by explicitly attaching to the channel earlier, calling presence on it when necessary, and explicitly detaching later we'd rather not remain attached to the channel longer than necessary and, in any event, it'd be nice if that race condition were resolved (if that is what's going on).

**Comment by mattheworiordan** [comment]
@paddybyers @amsurana can we look further into this issue?

**Comment by sacOO7** [comment]
It will be useful if I can get more info. on how to reproduce the issue : )

**Comment by sacOO7** [comment]
@QuintinWillison

**Comment by QuintinWillison** [comment]
Hello, @sacOO7, further detail from the customer ticket:

> I've attached a cleaned up test case and associated log file demonstrating the behavior. In the test, a parent app checks for presence repeatedly while a single child app remains attached to the channel the whole time. Even when presence.get(true) indicates that the child app is absent, messages are successfully delivered to and acted upon by the child app.

[Logs-with-redactions.txt](https://github.com/ably/ably-java/files/5161646/Logs-with-redactions.txt)
[Stripped_Down_Test_Case.java.zip](https://github.com/ably/ably-java/files/5161654/Stripped_Down_Test_Case.java.zip)

This is all we've got to work with on this one.

**Comment by sacOO7** [comment]
Ah, okay. I will look into it : )

**Comment by sacOO7** [comment]
There seems a problem with syncing, I will try to simulate the behaviour by writing the same test.

**Comment by sacOO7** [comment]
It's going to take more time ...

**Comment by sacOO7** [comment]
This issue is fixed as a part of #607
