### ISSUE TITLE
Lib is not re-sending pending messages on new transport after a resume

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#474]
Log posted by a customer [here](https://ably-real-time.slack.com/archives/C030C5YLY/p1558623828295800) (cf [conversation](https://app.intercom.io/a/apps/ua39m1ld/inbox/inbox/all/conversations/22156922233)) shows several issues:

1. At one point it disconnects the transport for inactivity at 14:29:08.086Z, 16s after getting a detached from realtime at 14:28:52.151. That shouldn't happen.
1. After it reconnects and resumes, it does not seem to be re-sending messages on the new transport that were pending on the previous transport, as required by RTN15f
1. Related to the previous one: messages called back with a failure due to getting an ack for a higher msgSerial than the pending queue are called back with "Unknown error / 50000 / 500", which could be more informative

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-430) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
The customer log contains some sensitive information so we're not able to attach it here.

However, I suggest that you start by creating a test for https://docs.ably.io/client-lib-development-guide/features/#RTN15f and see what happens, specifically relating to sending pending messages on a reestablished transport.

**Comment by amihaiemil** [comment]
@paddybyers I did a little research and I landed on [RealTimeResumeTest](https://github.com/ably/ably-java/blob/59100ab140c137f385dbb727c14e2643f4eb2cd7/lib/src/test/java/io/ably/lib/test/realtime/RealtimeResumeTest.java) -- as far as I understand, this is where we should add the test you propsed. Am I right, or at least close to it?  :D

**Comment by amihaiemil** [comment]
@SimonWoolf This ticket is rather old, but maybe you remember about it. I'm new to the project and currently trying to figure out the architecture/concepts etc. From what I understand, by "transport" you actually mean "channel", right?

**Comment by paddybyers** [comment]
@SimonWoolf btw we discussed ^

**Comment by paddybyers** [comment]
The bug is here, clear as day: https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L1209

Instead, queued messages should be reattempted, as per https://sdk.ably.com/builds/ably/specification/main/features/#RTN15c7

**Comment by paddybyers** [comment]
There's a further problem with the handling of the failed resume case. The spec (https://sdk.ably.com/builds/ably/specification/main/features/#RTN15c7) says that existing channels transition to `ATTACHING` (and init a new attach sequence) if there is a new connection established. However, this library is transitioning all channels to `SUSPENDED` (https://sdk.ably.com/builds/ably/specification/main/features/#RTN15c7). This will also prevent pending messages from being reattempted after connection.

**Comment by paddybyers** [comment]
> If I am not mistaken, that particular code block refers to `pendingMessages` while spec talks about `queuedMessages` which is a different one. I'm trying to confirm that those queued messages are published after reconnection but I wanted to check whether I understand that point correctly.

There are two mechanisms implemented in ably-java.

1. Queueing of messages in a Channel, if `ClientOptions.queueMessages == true`.
2. Handling of pending messages in the `ConnectionManager` that have been sent and are awaiting acknowledgement.

These are to meet two different requirements.

I do think the spec is potentially confusing, but see https://sdk.ably.com/builds/ably/specification/main/features/#RTN19a1 - using the same queue is an implementation option, but ably-java does not do this.

Nonetheless, the requirement is that messages in `ConnectionManager.pendingMessages` need to be reattempted on reconnection (whether the resume succeeded or not).

**Comment by SimonWoolf** [comment]
Note that this bug was fixed as part of the protocol v2 work, see https://github.com/ably/ably-java/pull/842/files#diff-dd49abde9c821fd279fba13b6207618933be4a96a7625f0378160b2187853de9R1510-R1530

**Comment by ikbalkaya** [comment]
Thank you @SimonWoolf. I think we can use those changes to fix issues related to connection resumption there but we cannot directly use that branch. Since changes on the  target a different branch, which has a different project structure and has breaking changes in it we won't be able to merge this in the near future. 
But I am thinking of picking of changes from there and apply it to another branch that  targets the main branch and then run @jaley's tests against those changes. I think this will probably be the quickest way to fix those resumption related issues without doing much work. WDYT?

**Comment by SimonWoolf** [comment]
> Since those changes target a different branch

It shouldn't, base should be changed to main per https://github.com/ably/specification/pull/119

> which has a different project structure

What do you mean by this?

> and has breaking changes in it we won't be able to merge this in the near future.

it has one breaking change, which per https://github.com/ably/ably-java/issues/868 should be made non-breaking before we merge it as a patch release

**Comment by ikbalkaya** [comment]
Before connection resumption / recovery changes there was another work to improve project structure. See https://github.com/ably/ably-java/pull/767 and [Aka-protocol-2.0 branch ](https://github.com/ably/ably-java/pull/842) is based on that. If I'm not mistaken the project restructure would cause breaking changes (class names, visibility etc) @QuintinWillison might shine more light on that but considering both PRs are on draft state, I do not think we can merge any of them soon.

**Comment by paddybyers** [comment]
@ikbalkaya I think using that branch as inspiration, and perhaps cherry-picking some of the code, would be a sensible way forward here

**Comment by SimonWoolf** [comment]
Yeah, that one was very poorly worded. That's why I rewrote it :slightly_smiling_face:

What it was trying to say was that if you're `suspended` you should start a normal attach (move to the `attaching` state and send an ATTACH), and if you're in `attaching` or `attached` you should send an ATTACH but not otherwise change state.

In the new spec, this becomes even simpler (`The client library should move all channels that were in the @ATTACHING@, @ATTACHED@, or @SUSPENDED@ states to the @ATTACHING@ state, and initiate an @RTL4c@ attach sequence for each.`).

(Again, this is all fixed in protocol-2. Is it really so unfeasable to rebase that branch on `main` so it can be released without breaking changes?)

**Comment by ikbalkaya** [comment]
> Is it really so unfeasable to rebase that branch on main so it can be released without breaking changes?

Not really, I actually did that (without adding tests - but tests could also be added easily).My concern was that that was still in draft state even if there are approvals. If other people are ok I can progress with bringing all changes from there.
