### ISSUE TITLE
PUSH_ACTIVATE intent broadcast is not always sent when activating push

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#477]
Without this, there is no way to know when to perform operations, such as push subscriptions, when those operations depend on activation having completed.

**Comment by paddybyers** [comment]
@amsurana did you get anywhere with this?

**Comment by amsurana** [comment]
Can we close this issue? I have tested and found it working as of today (July 8th). 
I believe 1.1.2 has the required fix.

**Comment by paddybyers** [comment]
It's referenced in the push-fixes branch, so it will close when that branch is merged.

**Comment by paddybyers** [comment]
Fixed by https://github.com/ably/ably-java/pull/485
