### ISSUE TITLE
fromCipherKey does not match spec

### ISSUE THREAD

**Issue by tomczoink** [ably/ably-java#492]
In the Java library there's a method `fromCipherKey`, however according to the spec it should instead be `withCipherKey` (https://docs.ably.io/client-lib-development-guide/features/#TB3). We should ensure the method matches the spec.

**Comment by paddybyers** [comment]
@amihaiemil are you able to look at this please? Check the spec for exactly what needs to be implemented. If an existing method in the library has the wrong name or signature, then it should be kept but annotated with `@deprecated`. Tests should exist for both the original and corrected API.

**Comment by amihaiemil** [comment]
@tomczoink PR #513 has been merged. I'm closing this. Thanks!
