### ISSUE TITLE
JSONUtilsObject.add() silently discards data of unsupported type

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#501]
If `value` has a type that doesn't translate naturally to a JSON value, then it is silently discarded: https://github.com/ably/ably-java/blob/develop/lib/src/main/java/io/ably/lib/util/JsonUtils.java#L34

This should at least log that event, and possibly throw an exception.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-434) by [Unito](https://www.unito.io)

**Comment by amsurana** [comment]
Pushed a PR #502

**Comment by QuintinWillison** [comment]
@ikbalkaya @KacperKluka @qsdigor I was just perusing our open, draft PRs and noticed #729. I expect it may well be the case that that particular PR is no longer viable, it probably needs rework / conflicts addressing - but what do we think to including this issue in [our 2.0.0 milestone](https://github.com/ably/ably-java/milestone/7)? It feels like a 'quick win' for correctness, right? 🤔

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-434
