### ISSUE TITLE
Upload to Maven Central

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#505]
We need the library and artifacts to be available on Maven Central.

We need to review what exists (https://github.com/ably/ably-java/blob/develop/java/maven.gradle) and decide the best way to enable maven deploys.

**Comment by mattheworiordan** [comment]
@paddybyers shouldn't this issue mention:

> Finally the ws client library we're using has been resurrected and is now being maintained: https://github.com/TooTallNate/Java-WebSocket

**Comment by paddybyers** [comment]
Yes, instead of also pushing `io.ably.Java_Websocket` to Maven, we will aim to migrate to use the latest `org.java-websocket.Java_Websocket`, which is already there.

**Comment by amihaiemil** [comment]
@paddybyers @mattheworiordan first things first, you need to create a namespace/groupid for your company. You need to register with Sonatype and open an Issue about that. Check this out:

https://www.youtube.com/watch?v=0gyF17kWMLg&feature=youtu.be (this is part of their official tutorial). 

You need to create a company account in their Jira tracker and open an Issue asking for the groupId **io.ably.***

The account and password you create are important as they will be used as credentials when publishing the artifacts. Later, you'll need to create a GPG key to sign the artifacts, but let's have the groupId first :)

**Comment by QuintinWillison** [comment]
v.1.1.8 was pushed [live](https://search.maven.org/search?q=g:io.ably) by @paddybyers using https://github.com/ably/ably-java/commit/e42bb9733cb33c2c8618d2ff1b2e3b05f43e9a95, which was further refined with https://github.com/ably/ably-java/commit/1ea6746c3d6cc8a86c264c110fc2c2ccaed8df4d and https://github.com/ably/ably-java/commit/d6fb580762cf24f1f56c9705b4bc6c9536e9706a (all via #560).

Thus, while there is other work that could be done, the core issue has been solved.
