### ISSUE TITLE
Github Pages docs website

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#507]
I noticed on Slack there is a lot of arguing on how the code samples should be organized. 

I suggest we build a website for each repository (I suppose each repo holds a library). The website can reside on the repository's **gh-pages** branch and it will automatically be deployed and hosted by Github (see [Github Pages](https://pages.github.com/)). 

I am no front-end developer so I can't design one, but surely there must be dozens of elegant templates for documentation website all over the internet. 

We could even design an annotation for the JUnit tests (say ``@Documented``) and a little tool to take the unit test and put it on the **gh-pages** branch automatically. This is based on the idea that, in OOP, a unit test can be seen as the documentation for the object under test (it shows how the object is created, used and what is its expected behaviour).

**Comment by amihaiemil** [comment]
@mattheworiordan let me know what you think :)

**Comment by mattheworiordan** [comment]
> I noticed on Slack there is a lot of arguing on how the code samples should be organized.

Yup, we like to debate :)

> I suggest we build a website for each repository (I suppose each repo holds a library). The website can reside on the repository's gh-pages branch and it will automatically be deployed and hosted by Github (see Github Pages).

I think you are referring to https://github.com/ably/docs, which is published to docs.ably.io (for internal development only), see channels docs for example at https://docs.ably.io/realtime/channels/, and select Java as the lang.

These docs are then in turn published to our primary website, where our customers and developers read our docs, see https://www.ably.io/documentation/realtime/channels/.

> We could even design an annotation for the JUnit tests (say @Documented) and a little tool to take the unit test and put it on the gh-pages branch automatically.

Sure, this is nice, but then we have two places for canonical docs.  I am not against inline docs in the API itself, but it should be lightweight and link to the canonical docs at https://www.ably.io/documentation.

> This is based on the idea that, in OOP, a unit test can be seen as the documentation for the object under test (it shows how the object is created, used and what is its expected behaviour).

Sure, but the world is not that "pure" I am afraid.   See https://www.ably.io/documentation/realtime/channels/ for example.  It has getting started docs, descriptions of how the channels work, then it has an API reference.  And those docs are shared between all SDKs.

P.S. I did try this with Ruby at https://github.com/ably/ably-ruby/blob/master/SPEC.md, but it was not good as you will see :)

What do you think?

**Comment by amihaiemil** [comment]
@mattheworiordan oh, I see. You have something bigger in place; I guess Github Pages don't make a lot of sense then. I'll have a look over your resources. Thanks! :)
