### ISSUE TITLE
Indentation and Line Length

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#509]
I notice the library is filled with TABs and lines the length of a few feet. From my experience:

* TABs should be replaced by 4 spaces and in general the indentation should be based on 4-space rule.  Because different IDEs and Web Views (e.g. Github) implement the TAB differently (more or less spaces), the code seems "thrown away" and not correctly indented.

* Line length of maximum 80 chars followed by an "open/close paranthesis" rule. An example bellow, from ``AblyBase``:

**ORIGINAL**
```java
private Http.Request<Long> timeImpl() {
		return http.request(new Http.Execute<Long>() {
			@Override
			public void execute(HttpScheduler http, Callback<Long> callback) throws AblyException {
				http.get("/time", HttpUtils.defaultAcceptHeaders(false), null, new HttpCore.ResponseHandler<Long>() {
					@Override
					public Long handleResponse(HttpCore.Response response, ErrorInfo error) throws AblyException {
						if(error != null) {
							throw AblyException.fromErrorInfo(error);
						}
						return Serialisation.gson.fromJson(new String(response.body), Long[].class)[0];
					}
				}, false, callback);
			}
		});
}
```

**4-space/80chars indentation**

```java
private Http.Request<Long> timeImpl() {
    return this.http.request(
        new Http.Execute<Long>() {
            @Override
            public void execute(
                HttpScheduler http, Callback<Long> callback
            ) throws AblyException {	
                http.get(
                    "/time",
                    HttpUtils.defaultAcceptHeaders(false),
                    null,
                    new HttpCore.ResponseHandler<Long>() {
                        @Override
                        public Long handleResponse(
                            HttpCore.Response response, ErrorInfo error
                        ) throws AblyException {
                            if(error != null) {
                                throw AblyException.fromErrorInfo(error);
                            }
                            return Serialisation.gson.fromJson(
                                new String(response.body), Long[].class
                            )[0];
	                }
                    },
                    false,
                    callback
                );
            }
        }
    );
}
```

These may seem like worthless cosmetic issues but in my experience they help a lot in making the code easier to understand, making design patterns more visible etc.

Furthermore, each class property should always be used with ``this.``,

These are all rules which can automatically be imposed via a static code analyzer, like **Checkstyle**.

**Comment by mattheworiordan** [comment]
> These may seem like worthless cosmetic issues but in my experience they help a lot in making the code easier to understand, making design patterns more visible etc.

Sorry, but you are proposing one style over the other, and that is subjective.  We use spaces in Ruby because that is idiomatic, and use tabs in Java, because that is mostly idiomatic.  There is no "right" solution.

If you want smaller tabs, all IDEs support that, i.e. you can set tabs to be presented as 2, 4 or 8 spaces.

In regards to tabs vs spaces, sure, I prefer spaces, and @paddybyers prefers tabs.  One being better than the other is subjective I am afraid.

We applaude Go for taking this decision away, but this is Java, that has not happened.

**Comment by amihaiemil** [comment]
@mattheworiordan I see; I'm closing this then :)
