### ISSUE TITLE
AblyRealtime should implement Autocloseable

### ISSUE THREAD

**Issue by amihaiemil** [ably/ably-java#514]
I noticed all or most of our tests for ``AblyRealtime`` have the ``try-catch-finally`` pattern, becuase the instantiated ``AblyRealtime`` objects need to be closed. I suspect that also in "real" usage, the object has to be closed when its no longer needed.

In order to simplify things, this class should implement [Autocloseable](https://docs.oracle.com/javase/7/docs/api/java/lang/AutoCloseable.html) and be used in ``try-with-resources``, which was introduced in Java 7. Then, the code can be simplified a lot for our clients and also in our tests. Instead of this:

```java
try {
    AblyRealtime ably = ...
} catch (AblyException ex) {
    fail(...);
} finally {
    ably.close();
}
```

we will have this:

```java
try (AblyRealtime ably = ...) {
    ...
} // we don't care about the exception anymore
//since the test will fail automatically and log
//the exception anyway, if it is thrown.
```

Note that this change will not affect backwards compatibility!

**Comment by paddybyers** [comment]
Is that going to be possible, given that we already declare `public void close()`  ?

**Comment by amihaiemil** [comment]
@paddybyers yes, it will be possible: implementors of an interface can choose to implement more specific methods: this means ``AblyRealtime.close()`` is fine as it is, we don't need to declare any ``throws Exception`` :)

It's also stated in Autocloseable's javadoc: 

```
While this interface method is declared to throw Exception,
implementers are strongly encouraged to declare concrete implementations
of the close method to throw more specific exceptions,
or to throw no exception at all if the close operation cannot fail.
```

**Comment by paddybyers** [comment]
Right, but it was the `public` bit I wasn't sure about.

**Comment by amihaiemil** [comment]
@paddybyers yes, ``public`` is fine, it's how it should be :)
