### ISSUE TITLE
Rework and reinstate invalid ConnectionManager tests

### ISSUE THREAD

**Issue by paddybyers** [ably/ably-java#524]
A number of tests (https://github.com/ably/ably-java/commit/e44341478a4d7e45f8767aa57e5c64ff17bbe496) are @Ignored because they do not lass reliably, and do not validly test the spec items that they purport to test.

**Comment by amihaiemil** [comment]
@paddybyers can I take this one?

**Comment by amihaiemil** [comment]
@QuintinWillison I've reopened this Issue because the merged PR didn't actually solve the problem entirely, it was WIP (issue was closed automatically due to the ``closes`` keyword in the description)

**Comment by paddybyers** [comment]
The tests in question are reworked as part of the work in https://github.com/ably/ably-java/tree/connectionmanager-sync-refactor.
