### ISSUE TITLE
ably-java sometimes failing to decrypt Messages

### ISSUE THREAD

**Issue by SimonWoolf** [ably/ably-java#531]
Customer reports that encrypted messages are occasionally unable to be decrypted:
```
2019-11-22 11:48:20.515 E/ABLY_INTERNAL: decrypt()
2019-11-22 11:48:20.515 E/ABLY_INTERNAL: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
2019-11-22 11:48:20.515 E/ABLY_INTERNAL: Unexpected exception: error:1e00007b:Cipher functions:OPENSSL_internal:WRONG_FINAL_BLOCK_LENGTH
```
It appears to be specific messages only, but those messages can apparently still _sometimes_ be successfully decrypted, but not other times.

Unclear whether the messages in question were published from ably-java or ably-cocoa, but it is one or the other. Also unclear whether the problem is limited to messages published by only one of those client libs, or both. So may be an ably-cocoa bug.

See internal channels for example of a raw message that sometimes can't be decrypted

**Comment by amihaiemil** [comment]
@SimonWoolf Can you please give more details about this Issue? What's the exact scenario when this happens (code flow?). Also, you say:

> See internal channels for example of a raw message that sometimes can't be decrypted

What are the "internal channels"?

**Comment by SimonWoolf** [comment]
> What are the "internal channels"?

Sorry if that was unclear -- I just meant our internal company slack. It's a bug report from a customer, the message can't be made public for data privacy reasons.

Re a test case -- no, one does not exist now, once we figure out what happens well enough to write a test that consistently reproduces the issue we'll be most of the way towards solving it :slightly_smiling_face:

@QuintinWillison is coordinating the response for this; liaise with him :slightly_smiling_face:
