### ISSUE TITLE
Formalise Coding Style

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#537]
Using [checkstyle](https://github.com/checkstyle/checkstyle) (or an alternative?) to help us.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-574) by [Unito](https://www.unito.io/learn-more)

**Comment by amihaiemil** [comment]
@QuintinWillison I could help you in this matter. I use checkstyle in most of my projects. [Here](https://github.com/amihaiemil/docker-java-api/blob/master/checkstyle.xml) is an example of checkstyle rules. They seem like a lot but most of them are basic stuff.

**Comment by QuintinWillison** [comment]
Hello @amihaiemil. I self-assigned the issue. If we need your help as a contractor, then we'll be in touch. Thanks.

**Comment by QuintinWillison** [comment]
[This](https://blog.overops.com/tabs-vs-spaces-how-they-write-java-in-google-twitter-mozilla-and-pied-piper/) is perhaps a starting point for the "tabs to spaces" decision.

I am biased, of course, towards spaces - whereas I know @paddybyers perhaps would like to keep tabs, which I think comes more from a Python / Go heritage.

**Comment by QuintinWillison** [comment]
Closing this issue as it's currently adding little value to our backlog.

We've had checkstyle in place since https://github.com/ably/ably-java/pull/609, and now we just need to iteratively take advantage of it by adding rules over time as needs arise or time allows.
