### ISSUE TITLE
Avoid message bundling, conforming to updated RTL6d

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#548]
See [RTL6d](https://docs.ably.io/client-lib-development-guide/features/#RTL6d), as amended by this [docs PR](https://github.com/ably/docs/pull/788#issuecomment-581490475).

There may be no work to do if this client library already doesn't bundle messages, however I've not got time to investigate that right now so am creating the issue so that investigation can take place followed by remediation if required.

**Comment by QuintinWillison** [comment]
For reference, see the equivalent [ably-js issue](https://github.com/ably/ably-js/issues/629) which includes commentary describing how it had already been resolved and a link to the [relevant pull request](https://github.com/ably/ably-js/pull/623).

**Comment by SimonWoolf** [comment]
@QuintinWillison Have a customer experiencing an issue https://support.ably.io/a/tickets/105601 that implies that ably-java is currently merging in violation of RTL6d7. https://github.com/ably/ably-java/blob/master/lib/src/main/java/io/ably/lib/transport/ConnectionManager.java#L1409-L1416 . I suggest just removing those lines altogether and cutting an ably-java release as a priority. That should be a safe change.

**Comment by QuintinWillison** [comment]
Thanks for investigating, @SimonWoolf. I'll take a look.
