### ISSUE TITLE
Review JDK 7 and Android API Level requirements

### ISSUE THREAD

**Issue by tcard** [ably/ably-java#555]
[For instance](https://travis-ci.org/ably/ably-java/jobs/647991348)

```
FAILURE: Build failed with an exception.
* What went wrong:
Gradle 5.2.1 requires Java 8 or later to run. You are currently using Java 7.
```

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-577) by [Unito](https://www.unito.io)

**Comment by paddybyers** [comment]
I don't think we should be testing against Java 7 any more

**Comment by QuintinWillison** [comment]
I think we should first review the "Supported Platforms" as specified in the [README](https://github.com/ably/ably-java/blob/master/README.md). If we're promising `Java7+` then we should find a way to test with that.

**Comment by paddybyers** [comment]
I agree that what we do should of course align with what we claim :) My point is that I think supporting Java 7 is probably no longer necessary, so we should stop doing it, and stop claiming it.

**Comment by QuintinWillison** [comment]
Relates to #554 

Also related is this is our minimum Android version required at runtime. The support for selecting this when you create a project in Android Studio has, from what I can see, improved quite a lot:

![Screenshot 2020-06-29 at 16 21 01](https://user-images.githubusercontent.com/8318344/86024602-165d7000-ba25-11ea-84a1-6d7948525956.png)

We should definitely use this as guidance, in that this may be the first data an app developer sees when it comes to establishing their baseline runtime requirements for a new app.

**Comment by QuintinWillison** [comment]
Also see [Use Java 8 language features and APIs](https://developer.android.com/studio/write/java8-support) (Android Studio Docs)

**Comment by sacOO7** [comment]
For me. while running build using the latest Gradle version on main, gives following problem 
```> Cannot perform signing task ':java:signArchives' because it has no configured signatory```
Java version - 1.8
