### ISSUE TITLE
Address impact of change to interface on extras field on Message

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#580]
For [1.2.0](https://github.com/ably/ably-java/releases/tag/v1.2.0) we changed `Message.extras` from `JsonObject` to `MessageExtras`.

This was a breaking change which [we acknowledged as a TODO](https://github.com/ably/ably-java/blob/b53dc120ef67999e6a48700fedf3bc5176eaa20f/lib/src/main/java/io/ably/lib/types/MessageExtras.java#L15) but never addressed.

We need to decide the approach for fixing this (either revert or extend the new `MessageExtras` class) in order to comply with [TM2i](https://docs.ably.io/client-lib-development-guide/features/#TM2i).

**Comment by kavalerov** [comment]
Which approach is faster to implement? And what are the downsides of keeping `JsonObject`?

**Comment by paddybyers** [comment]
Honestly I think extending `MessageExtras` is the way to go.

**Comment by mattheworiordan** [comment]
Why does this need to be a `MessageExtras` object when it's defined in the spec as JSON object?

**Comment by mattheworiordan** [comment]
Related https://github.com/ably/docs/issues/652.

**Comment by SimonWoolf** [comment]
I have to agree with Matt - the spec item envisaged a json blob, opaque to the client library, so we could add new features without having to make painful client lib changes, or have to encode the knowledge of how all the push payloads are structured, etc. I haven't seen anyone give a good reason for us to change that plan. (Of course typed languages might well want to parse extras.delta on incoming messages into a DeltaExtras object before interacting with it, but they can still do that)

**Comment by mattheworiordan** [comment]
@QuintinWillison are there any other SDKs which have gone down this route in 1.2 and deviated from the spec?

**Comment by QuintinWillison** [comment]
@mattheworiordan off topic for this issue and repository context. Moved to [internal Slack conversation](https://ably-real-time.slack.com/archives/C030C5YLY/p1591772640363700) for the moment, until we have an explicit issue or issues to create in other repositories. Thanks.
