### ISSUE TITLE
FCM getToken method is deprecated

### ISSUE THREAD

**Issue by cruickshankpg** [ably/ably-java#597]
Currently when getting the registration token from FCM we use https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#public-string-gettoken which is now deprecated. We should call https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId#public-string-gettoken-string-senderid,-string-scope instead but would need a way for clients to provide the allowed senderIDs.

For ref of where we're doing this:
https://github.com/ably/ably-java/blob/756f52b0b1c92042f22c637ef736877630b6d554/android/src/main/java/io/ably/lib/push/ActivationContext.java#L138

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-590) by [Unito](https://www.unito.io)

**Comment by MazyNoc** [comment]
It's now even worse, in firebase messagaging library 22.0.0 the whole FirebaseInstanceId has been removed and you will get a runtime crash with Ably.

**Comment by ben-xD** [comment]
The PR has been merged, but the runtime crash will exist until this is released.

A temporary workaround is to add the following to your `app/build.gradle`:
```
implementation 'com.google.firebase:firebase-iid:21.1.0'
```

**Comment by ben-xD** [comment]
This PR has been released, make sure to use 1.2.7 or newer to avoid this problem.
