### ISSUE TITLE
Defaults: Generate environment fallbacks

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#603]
Per `RSC15g`, introduced in https://github.com/ably/docs/pull/965.

See https://github.com/ably/ably-js/pull/682 and https://github.com/ably/ably-ruby/pull/196 for reference implementations.

**Comment by sacOO7** [comment]
I have added few comments on https://github.com/ably/ably-js/pull/682 based on https://github.com/ably/docs/pull/965 (js client might be missing a few things from spec)
