### ISSUE TITLE
Dead channels after reconnection

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#605]
_We've had a report from a customer, [via Intercom](https://app.intercom.com/a/apps/ua39m1ld/inbox/inbox/all/conversations/38483300001157). Conversation detail, with redactions:_

CUSTOMER: I have an issue with 1.2.1 of the ably java library and that's after several disconnection events, some channels are alive, and some are dead. 
I run multiple channels, for dedicated outgoing and incoming messages. the incoming is dead after reconnect.
that results in trying to push queue messages forever, resulting in a ton of message throughput and a lot of unnecessary cost

CUSTOMER: the 2 first channels are send, and receive channel. the send is alive but receive is dead.I only create the channels once. I think I have had issues earlier like this

**Paddy from Ably**: Hi. We can look into this. Are you able to capture a verbose log?

CUSTOMER: these are production units I have to immediately restart

CUSTOMER: it's very hard to reproduce. it just has to happen on a crappy connection

CUSTOMER: it's fine for a good while, then we detect that there's a queue buildup that doesn't get answered

CUSTOMER: there should never be a "dead" channel right

CUSTOMER: I certainly don't expect it to happen

CUSTOMER:

```
31.08.20 14:19:08 (+0200) <controller> 2020-08-31T12:19:08,923Z [Thread-3008] INFO com.customer.app.AblyTransport - Connection state changed to 'disconnected' from 'connected'. Reason: '[ErrorInfo message=Connection superseded. (See https://help.ably.io/error/20000 for help.) code=20000 statusCode=204 href=https://help.ably.io/error/20000]'.
```

CUSTOMER: this problem happens when it flips between disconnected and connection

CUSTOMER:

```
31.08.20 14:25:13 (+0200) <controller> 2020-08-31T12:25:13,821Z [Thread-3008] INFO com.customer.app.AblyTransport - Connection state changed to 'connecting' from 'connected'. Reason: 'null'.
31.08.20 14:25:13 (+0200) <controller> 2020-08-31T12:25:13,822Z [Thread-3008] WARN com.customer.app.GreenContactTransport - Green Contact Transport disconnected
31.08.20 14:25:15 (+0200) <controller> 2020-08-31T12:25:15,909Z [Thread-3008] INFO com.customer.app.AblyTransport - Connection state changed to 'connected' from 'connecting'. Reason: 'null'.
31.08.20 14:25:15 (+0200) <controller> 2020-08-31T12:25:15,909Z [Thread-3008] INFO com.customer.app.GreenContactTransport - Green Contact Transport connected
31.08.20 14:25:16 (+0200) <controller> 2020-08-31T12:25:16,437Z [Thread-3008] INFO com.customer.app.AblyTransport - Connection state changed to 'disconnected' from 'connected'. Reason: '[ErrorInfo message=Connection superseded. (See https://help.ably.io/error/20000 for help.) code=20000 statusCode=204 href=https://help.ably.io/error/20000]'.
31.08.20 14:25:16 (+0200) <controller> 2020-08-31T12:25:16,437Z [Thread-3008] WARN com.customer.app.GreenContactTransport - Green Contact Transport disconnected
31.08.20 14:25:16 (+0200) <controller> 2020-08-31T12:25:16,972Z [Thread-3008] INFO com.customer.app.AblyTransport - Connection state changed to 'connecting' from 'disconnected'. Reason: 'null'.
31.08.20 14:25:19 (+0200) <controller> 2020-08-31T12:25:19,157Z [Thread-3008] INFO com.customer.app.AblyTransport - Connection state changed to 'connected' from 'connecting'. Reason: 'null'.
```

CUSTOMER: it had this dead channel before this message too, but

**Paddy from Ably**: Thanks. That looks like a pretty messy sequence of events :grinning: 
 The "Connection superseded" message is saying that the library reconnected after having been disconnected for a period of time - but when that happened the earlier connection state had expired, so a new connection was created. When that happens, it is supposed to explicitly re-attach all of the channels that had been attached previously. That functionality is definitely supported but it is possible that there's a bug there. Or, from the log, it's possible that such a rapid sequence of state changes is causing state transitions to occur before the processing for the previous transition is complete, and that might be exposing some bugs. 
 We'll have a look and let you know what we find.

CUSTOMER: thanks! try to stresstest this . these devices run in parking garages with crappy 4G coverage.

CUSTOMER: and I need to know what workaround can work

**Paddy from Ably**: In terms of workarounds: what I can suggest is that when you get a connected event, you explicitly attach() the channels - that should happen automatically, but it might work around the problem if, due to some race condition, it's not happening. In any case, if you do find instances of channels that are not being reattached, then that would be useful information.

CUSTOMER: thanks. is there a check on whether they are attached or not ?

**Paddy from Ably**: Channel.state will give you the current state, plus you can listen for channel state changes.

CUSTOMER: OK

CUSTOMER: so I attach to the event handler this.ably.connection.on(this::onConnectionStateChanged);

CUSTOMER: so in case connected: - I should attach all channels again, to be sure?

CUSTOMER: since this is in the event handler, it won't cause further concurrency issues? (if the event handler is from a thread or something)

**Paddy from Ably**: That's a good question. I don't think it should cause a problem. 
 I want to know more about what you're seeing when you say "some channels are dead". Is it that you just don't receive any messages? In that case can you check the channel state, at least?

CUSTOMER: I am not sure they are properly detached, so I can check the status, it happens more rarely now so the testing will take time because I can't reproduce it without it naturally happening in the field

**Paddy from Ably**: ok. If you do find anything, let us know.

_Internal ticket: [SDK-96](https://ably.atlassian.net/browse/SDK-96)_

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-447) by [Unito](https://www.unito.io)

**Comment by sacOO7** [comment]
In the log, it mentions disconnected with error code 20000. Spec mentions disconnection will happen with an error code in the range 40140 <= code < 40150.
https://docs.ably.io/client-lib-development-guide/features/#RTN22a

I am not sure if logs are specified in chronological order. But if they are, then the problem might be from the server-side itself.

**Comment by sacOO7** [comment]
Also, I am not able to find documentation for error code 20000. https://help.ably.io/error/20000

**Comment by sacOO7** [comment]
com.customer.app.AblyTransport seems to be a custom class, therefore these are custom log messages, rather than library logs

**Comment by sacOO7** [comment]
I was going through the code. It seems the channel will always attach itself whenever a new connection is created.

**Comment by SimonWoolf** [comment]
> Spec mentions disconnection will happen with an error code in the range 40140 <= code < 40150. https://docs.ably.io/client-lib-development-guide/features/#RTN22a

Those are the error codes for a disconnection _for a reason of auth token invalidity or expiry_. Those are far from the only reasons that the server may disconnect a transport.

https://github.com/ably/ably-common/blob/main/protocol/errors.json lists most of them. 20000 is a generic code meaning 'this is not actually an error'; in this case it's delivered for a transport being closed due to the connection being superseded. What that means is that if someone makes a resume or recover /connect request with a connectionKey for a connection, that becomes the active transport for that connection, and the server will disconnect any other existing transports for the connection, so there's only one active transport. (The assumption is that if the client is trying to resume on a new websocket, it's already given up on the previous websocket, so the server closes it from its end with a 20000/204 reason). If that is appearing on a transport that the client lib thinks is still the active transport, that indicates that the client library is trying to open a new socket (and resuming) while the previous one is still open. (Or possibly that the customer is opening a new client with a `recover` option set to the recoveryKey of an existing still-active client, but that's presumably not the case here).

Logs that only show the actual connection state change are not sufficient to see what the library is actually doing wrt resume/recover requests. We should ask the customer for Log.VERBOSE logs.

**Comment by sacOO7** [comment]
Convo link - https://ably-real-time.slack.com/archives/C030C5YLY/p1602076377057600
