### ISSUE TITLE
AuthOptions constructor is not unambiguous

### ISSUE THREAD

**Issue by gokhanbarisaker** [ably/ably-java#62]
AuthOptions constructor takes a string argument, which may be a key or a token. That makes the constructor argument ambiguous.

We may prevent this by changing constructor accessiblity to private and using builder pattern

**Comment by paddybyers** [comment]
The other libraries address this by looking at the string and deciding whether it is a key or a token.

**Comment by mattheworiordan** [comment]
@gokhanbarisaker I don't think a different pattern is needed given, as Paddy says, every other client library uses this approach and simply analyses the string provided to work out what it is. We do something similar for Authentication with an `authUrl` in that we detect the response as being a `TokenDetails`, `TokenRequest`, or token string.
