### ISSUE TITLE
Typo on Presence#history javadoc

### ISSUE THREAD

**Issue by gokhanbarisaker** [ably/ably-java#63]
`relates` misspelled as `relqtes` on https://github.com/ably/ably-java/blob/d668973bbd89b5ca5ef836937ef7d32fce5a9aab/lib/src/main/java/io/ably/lib/realtime/Presence.java#L286

**Comment by mattheworiordan** [comment]
May as well just fix and do a PR no?

**Comment by gokhanbarisaker** [comment]
I just wanted to add it here as a reminder. I will do it once I finish my current task.
