### ISSUE TITLE
Conform toString() implementations

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#631]
Match IntelliJ IDEA's boilerplate form, except where there's a reason to present some kind of native representation (e.g. JSON).

See [this thread](https://github.com/ably/ably-java/pull/623#discussion_r526795705).

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-592) by [Unito](https://www.unito.io)

**Comment by vzhikserg** [comment]
I would like to suggest to use a third-party library called [lombok](https://projectlombok.org/). It helps to automatically generate a log of the boilerplate code (toString, equal, hashcode, and so on). The library is used only at compile time. It is published under the MIT license.

Example:
If we add the lombok `@ToString` annotation for the [MessagExtras](https://github.com/ably/ably-java/blob/0e4da0f8ef63524b6fdc72e3d1a80561acf329d1/lib/src/main/java/io/ably/lib/types/MessageExtras.java#L20) class it will  generate the following output:

    MessageExtras(delta=null, jsonObject={"someKey":"someValue"})
