### ISSUE TITLE
on(ConnectionState, listener) marked as deprecated but used in documentation

### ISSUE THREAD

**Issue by Yoshi2889** [ably/ably-java#640]
In the README under Connection ( https://github.com/ably/ably-java#connection ) a method to listen to specific events is listed. However, it is marked as deprecated in the Connection class among `emit` and `once`:

https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/realtime/Connection.java#L105-L118

This is confusing. Either the documentation should be updated to include the `getConnectionEvent()` call, or these methods should not be marked as deprecated.

I am unsure why they would have been marked as deprecated in the first place, these seem like useful convenience methods.

**Comment by markcoxsmith** [comment]
Hi @Yoshi2889 , Thanks a lot for your comment here and I will pass this onto our documentation team

**Comment by GBR-422777** [comment]
Issue is still there...

**Comment by AndyTWF** [comment]
Hi @GBR-422777 thanks for the info, I'm updating the docs site in https://github.com/ably/docs/pull/1912 :)
