### ISSUE TITLE
capability tokendetails adds to HTTP Request as a query parameter  

### ISSUE THREAD

**Issue by rawandsaeed** [ably/ably-java#647]
I'm trying to request a token from an authUrl `authUrl = "htttps://sample.com/auth"`
For some reason when initiating the call Ably HTTP call adds `capability` as a query parameter. 
`https://sample.com/auth?capability=`
Is there anyway to remove this query parameter? Thanks

**Comment by QuintinWillison** [comment]
Hello @rawandsaeed ... we've had a quick look at this and you may be on to something, specifically relating to [this line](https://github.com/ably/ably-java/blob/f5e8466c99f5ad453a1e0682eb460ee83b9bca36/lib/src/main/java/io/ably/lib/rest/Auth.java#L570). Other client libraries don't set this unless it's not-empty (i.e. not `null`) so the implementation does look wrong.

I can't personally look at this in more depth today but we will get this issue fixed. Thanks for the report! 😁

**Comment by rawandsaeed** [comment]
Hello @QuintinWillison  thanks for the quick reply. I configured my server to accept this query parameter as null and it fixed my bug. I'm happy it is fixed now on Ably's end as well.
