### ISSUE TITLE
Hosts class is not thread safe

### ISSUE THREAD

**Issue by jahlbornG** [ably/ably-java#650]
The Hosts class is used by various threads when making api calls, however, the internals of this class are not handled in a thread safe way.  the various calls to manipulate the primary and preferred hosts and the expirations will not work correctly for more than one thread at a time.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-651) by [Unito](https://www.unito.io/learn-more)

**Comment by QuintinWillison** [comment]
Fixed in [version 1.2.5](https://github.com/ably/ably-java/releases/tag/v1.2.5), released today.
