### ISSUE TITLE
Crypto.getRandomMessageId isn't working as intended

### ISSUE THREAD

**Issue by jahlbornG** [ably/ably-java#654]
the value being generated by this method is returning the toString result of a char[], which probably is not the intended "random" value.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-659) by [Unito](https://www.unito.io/learn-more)

**Comment by sacOO7** [comment]
Okay, can you put here the value being generated? and the ideal random string value

**Comment by jahlbornG** [comment]
the current output is something like "[C@2669b199".  i assume the _intented_ result is the actual base64 encoded random value.

**Comment by sacOO7** [comment]
Okay, can you put here a link to the code, or filename, line no

**Comment by jahlbornG** [comment]
https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/util/Crypto.java#L324

**Comment by sacOO7** [comment]
Okay, let me check

**Comment by sacOO7** [comment]
Okay, I was able to reproduce the issue. Also, found the explanation for the same 
https://stackoverflow.com/questions/18625170/java-char-tostring. 
I will create a PR to fix it right away

**Comment by sacOO7** [comment]
`String.valueOf(Base64Coder.encode(entropy))` should fix the issue

**Comment by jahlbornG** [comment]
or you could use the existing method for that, Base64Coder.encodeToString()

**Comment by QuintinWillison** [comment]
Fixed in [version 1.2.5](https://github.com/ably/ably-java/releases/tag/v1.2.5), released today.
