### ISSUE TITLE
Deploy to Maven Central from GitHub Actions

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#659]
I've got a [skeletal workflow](https://github.com/ably/ably-java/blob/main/.github/workflows/assemble.yml) in place, and we were for a while even [showing the status badge](https://github.com/ably/ably-java/commit/4cd5f1bba3b2a7e7214ad1dc08a37c67fc64955a) (failing) with optimism that we would very soon find the time to fix it.

Scheduling fixing this issue is likely to be in the order of weeks or months, not days. Hence, I've created this issue for visibility and will remove the status badge for this workflow for now.

I have ideas around how we might implement a release procedure for continuous delivery, but how we approach this is a wider discussion for all of our SDKs - not just this one.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-662) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
I removed the placeholder skeleton in https://github.com/ably/ably-java/commit/68477899d2b67f564517c9368bec4e71c2f03547 and the badge in https://github.com/ably/ably-java/commit/6b4be7fe4be0bdff21b0853a006d99c46783b55b, given we've been unable to prioritise fixing this yet.

**Comment by QuintinWillison** [comment]
The opening comment on this issue is somewhat out-of-date, however the fundamental outcome remains the same. We need our release procedure for this SDK to operate entirely from the GitHub Actions environment - akin to what we already have in place [in AAT (publish workflow)](https://github.com/ably/ably-asset-tracking-android/blob/main/CONTRIBUTING.md#release-process). @KacperKluka has a solid understanding of this and is likely to want to work on this after he's finished his current Gradle refactor.

**Comment by KacperKluka** [comment]
Closing as an appropriate workflow was added in https://github.com/ably/ably-java/pull/791
