### ISSUE TITLE
handling of channel options in InternalChannels.get is not thread safe

### ISSUE THREAD

**Issue by jahlbornG** [ably/ably-java#663]
This is broken out of #649 . In both of the InternalChannels implementations, there is the following thread safety issue with the channel options handling:

Thread1 calls get() for Channel "foo" with ChannelOptions1 (with encrypted = false).
Thread2 calls get() for Channel "foo" with ChannelOptions2 (with encrypted = true).

Since Thread1 and Thread2 share the same Channel instance, Thread1 is now holding a Channel with ChannelOptions2 and is getting different behavior than it originally had. not to mention that the options are not set using anything which guarantees valid thread visibility rules, so when Thread1 uses ChannelOptions2, they may appear incompletely initialized.

┆Issue is synchronized with this [Jira Research](https://ably.atlassian.net/browse/SDK-670) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
We should look at this issue when we look at https://github.com/ably/ably-java/issues/570.

**Comment by QuintinWillison** [comment]
Channel get with options ([RSN3c](https://sdk.ably.com/builds/ably/specification/main/features/#RSN3c)) is "soft-deprecated" and so this method will be removed soon, hopefully under https://github.com/ably/ably-java/issues/831, as part of the v2 release.
