### ISSUE TITLE
Detaching connection listeners in onAuthUpdated 

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-java#668]
After landing PR https://github.com/ably/ably-java/pull/652 in the release of version `1.2.4` a [change](https://github.com/ably/ably-java/pull/652/files#diff-8c6da0b50c7444796d898484ceea059721a12b87e7de0c07546567c2fc91df23R969-R971) was made that [detaches all connection listeners](https://github.com/ably/ably-java/pull/652/files#diff-8c6da0b50c7444796d898484ceea059721a12b87e7de0c07546567c2fc91df23R509) after the `onAuthUpdated` method of the `ConnectionManager` finishes. I think that it's a bug and we shouldn't detach those listeners. However, if this is a thing that we want to do then at least let's document that in the javadocs.

@sacOO7 I was informed that you could help with that :wink:

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-719) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
If there's any guidance on this in the [features spec](https://docs.ably.io/client-lib-development-guide/features/) then we should adhere to that. Also, if this is something that needs documenting then it may also need to be added to the spec.

**Comment by KacperKluka** [comment]
After giving it a second look and a second thought it looks like everything is fine. I've been wrong and [this code](https://github.com/ably/ably-java/pull/652/files#diff-8c6da0b50c7444796d898484ceea059721a12b87e7de0c07546567c2fc91df23R509) doesn't detach all listeners but only the one that was connected for the `ConnectionWaiter` which is perfectly fine :+1:
