### ISSUE TITLE
IllegalArgumentException: No enum constant io.ably.lib.http.HttpAuth.Type.BASİC

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#711]
We've had a customer report this fatal exception at runtime. They're only seeing it on some users' Android devices - specifically a [Huawei Mate 10 Lite](https://www.gsmarena.com/huawei_mate_10_lite-8857.php).

The customer has provided us with a stack trace:

```
Fatal Exception: java.lang.IllegalArgumentException: No enum constant io.ably.lib.http.HttpAuth.Type.BASİC
       at java.lang.Enum.valueOf(Enum.java:257)
       at io.ably.lib.http.HttpAuth$Type.valueOf(HttpAuth.java:20)
       at io.ably.lib.http.HttpAuth.sortAuthenticateHeaders(HttpAuth.java:49)
       at io.ably.lib.http.HttpCore.handleResponse(HttpCore.java:337)
       at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:270)
       at io.ably.lib.http.HttpCore.httpExecute(HttpCore.java:165)
       at io.ably.lib.http.HttpCore.httpExecuteWithRetry(HttpCore.java:83)
       at io.ably.lib.http.HttpScheduler$AsyncRequest.httpExecuteWithRetry(HttpScheduler.java:312)
       at io.ably.lib.http.HttpScheduler$AblyRequestWithFallback.run(HttpScheduler.java:205)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

The customer also tells us:

> We tried to diagnose this previously be updating to the latest version of the ably sdk 1.2.7 and also updated our proguard/r8 rules as follows:

    -keep class io.ably.lib.http.**

The suspect call site ([here](https://github.com/ably/ably-java/blob/009e2bda402efe1aef6bab8eb5915bbc70fbb134/lib/src/main/java/io/ably/lib/http/HttpAuth.java#L49)) really doesn't provide much insight into failure of the call to `Type.valueOf` - so a theory is that the prior `trim()` on `authType` wasn't enough to cater for a runtime / device / connection variance of some sort.

See [internal Slack thread](https://ably-real-time.slack.com/archives/CLL6AEQS1/p1631200789002700).

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1174) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
As you've mentioned the issue is probably with the `Type.valueOf()`, but look at the error info and the word `BASIC`. If you look closely you can see that the `I` is in fact some strange letter `İ` :thinking: That's why an error is thrown, there's no "BASİC" enum value, the correct name is "BASIC". :wink:

**Comment by QuintinWillison** [comment]
After discussion with the wider team, I think @SimonWoolf may have identified what's going on here...

> raising another possiblity here: if Java `String`'s `toUpperCase()` functionality is locale-specific, and the user in question is running it a Turkish (or Azrbeijani or Kazakh) locale, and that might be taking a normal, correct `www-authenticate: basic` header received from a server and turning it into `BASİC`, which is apparently the correct Turkish capitalization of "i" (see [here](https://en.wikipedia.org/wiki/Dotted_and_dotless_I)).

To quote the **Note** from [the String API documentation](https://developer.android.com/reference/java/lang/String#toUpperCase(java.util.Locale)):

> This method is locale sensitive, and may produce unexpected results if used for strings that are intended to be interpreted locale independently. Examples are programming language identifiers, protocol keys, and HTML tags. For instance, `"title".toUpperCase()` in a Turkish locale returns `"T\u0130TLE"`, where '\u0130' is the LATIN CAPITAL LETTER I WITH DOT ABOVE character. To obtain correct results for locale insensitive strings, use `toUpperCase(Locale.ROOT)`.

So, I think the fix for this issue will be for us to use `Locale.ROOT` as described in that note, though I would want to see that unit tested for this particular failure in order to validate the fix, which will in turn require some refactoring of the implementation.

Perhaps we should consider making a discrete, focussed fix for this specific failure seen "in the wild", and then work on a subsequent wider change for all uses of `toUpperCase` or `toLowerCase` (well, any locale-sensitive `String` APIs).
