### ISSUE TITLE
Using Firebase installation ID as registration token: Users cannot reactivate the device after deactivating

### ISSUE THREAD

**Issue by ben-xD** [ably/ably-java#715]
~https://github.com/ably/ably-java/pull/687/files introduced a bug~. To get new FCM registration tokens, Ably Java calls FirebaseInstallations.getInstance().getToken(true) to get registration tokens. These are **not** registration tokens, these are 
> valid authentication token for the Firebase installation - [javadoc](https://github.com/firebase/firebase-android-sdk/blob/443d6e74da404925b15cc0b62963584c537e23ef/firebase-installations/src/main/java/com/google/firebase/installations/FirebaseInstallations.java#L203-L210)

Here's how we use it now:
```java
    protected void getRegistrationToken(final Callback<String> callback) {
        Log.v(TAG, "getRegistrationToken(): callback=" + callback);
        FirebaseInstallations.getInstance().getToken(true) // <---That doesn't give a registration token.
                .addOnCompleteListener(new OnCompleteListener<InstallationTokenResult>() {
                    @Override
                    public void onComplete(Task<InstallationTokenResult> task) {
                        Log.v(TAG, "getRegistrationToken(): firebase called onComplete(): task=" + task);
                        if(task.isSuccessful()) {
                            /* Get new Instance ID token */
                            String token = task.getResult().getToken();
                            callback.onSuccess(token);
                        } else {
                            callback.onError(ErrorInfo.fromThrowable(task.getException()));
                        }
                    }
                });
    }
```

This method is only called when a registration token was not provided to Ably by the OS in the onNewToken in FirebaseMessagingService, for example in the example Android app for Push: https://github.com/ably/push-example-android/blob/180ab65b1a418c0733157bdf78ddb85b06431033/app/src/main/java/io/ably/example/androidpushexample/AblyPushMessagingService.java#L20-L24

Therefore, it only affects the case where a user activates twice, or more. For example, they may activate, deactivate and deactivate. 

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1182) by [Unito](https://www.unito.io)

**Comment by ben-xD** [comment]
## As a solution

I propose not **deleting** the `registrationToken` when a device is reset. There is no known way to get a **new** registration token without the user actually reinstalling the app (or doing other things).

**Comment by paddybyers** [comment]
> I don't know a way to get a **new** registration token

Are you saying you can't re-obtain a previously-issued token? Or you can, just not get a different one?

**Comment by ben-xD** [comment]
Actually both are not possible straight out of the box/ firebase SDK anymore. But getting the **old**/ **existing** one is easy, just save it into [shared preferences](https://stackoverflow.com/a/41515597/7365866).

Bur my point is refreshing the token. Getting a new registration token string not equal to the old string.

**Comment by paddybyers** [comment]
Why would you need to get a different one?

**Comment by ben-xD** [comment]
Because this was the original implementation.

**Comment by ben-xD** [comment]
Oh my! I just realised it was https://github.com/ably/ably-java/pull/687/files that introduce the bug. This library has always had the bug. Before that PR, it used: `FirebaseInstanceId.getInstance().getInstanceId()` to get the `InstanceIdResult`. It used [`getToken()`](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/InstanceIdResult#getToken()) on this, but this is not the **registration token**, it is the token that authorizes performing actions on behalf of this application instance. 

@martin-morek, it wasn't your bug :).
