### ISSUE TITLE
Split library into core and platform modules

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-java#728]
We want to start restructuring ably-java project so that;
* We properly expose public facing APIs and hide the internal ones
* Separation of concerns
* Independent tasks / workflows for platforms as they might have different requirements.
* Make it easy to create new modules as required.

As a starting point we want to it into these three Gradle modules
* core 
* java
* android

* Core module would contain core library code
* Java module would contain public facing APIs
* Android module would contain public facing APis + additional features for Android platform 

Doing this would make it clear for us what to expose to developers of specific platforms. For example I don't currently see a reason why we would expose anything in the core module as it would be intended to build the public facing modules.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1316) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
I've investigated the possibility to improve the project Gradle structure and here are my thoughts:
- At the moment we have 2 modules `java` and `android` which use a common code declared in the `lib` folder which is then added to their source sets. 
- Both modules have the same package name `io.ably.lib.*`. 
- When you attempt to create a third module called `common` out of the `lib` folder you will discover that code there is highly coupled to `java` and `ably` modules as the code from the `lib` folder references classes defined in `java` and `android` (namely: `Push`, `AblyRest`, `Channel`, `Platform`)

I think that the `lib/common` should not be aware of anything besides itself but with the current level of coupling that's not possible to do. To solve it we should create some kind of abstract classes or interfaces for each of the troublesome references from `java` and `android` and use them in the `lib/common`, however, this will mean an API change as those classes are already exposed and used in `ably-java` public API.
