### ISSUE TITLE
Exit blocked by Ably Realtime when main thread exits 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#73]
See https://github.com/ably/ably-java/pull/52#issuecomment-169644640

We need to ensure that the threads for Ably are killed when the main thread has exited

**Comment by mattheworiordan** [comment]
@gokhanbarisaker @paddybyers apparently this is still happening.

> The Java SDK has a dangling thread on shutdown (I'm using a servlet under Tomcat).
> I see this: https://github.com/ably/ably-java/issues/73, says issue closed. But I see it. I'm calling ably.close(). I tried waiting for the connection state to transition to closed, before exiting, but made no difference.
> I'm using the latest jar file (full 0.8.2).

Can we look into this ASAP please?

**Comment by paddybyers** [comment]
> I tried waiting for the connection state to transition to closed, before exiting

Do you know if the `closed` state was reached? Once that happens, the `ConnectionManager` thread should exit. If you want a short term workaround we could provide a way to force the `ConnectionManager` thread to be a daemon but I definitely want to understand why it's not exiting.

Is there any chance you're blocking in one of the connection state callbacks?

**Comment by gokhanbarisaker** [comment]
hi @mattheworiordan ,

I have profiled the v0.8.2 with both `Android` & `Tomcat`. It seems like all threads are getting cleared

The test behavior is,
- `Connect to ably`
- `Attach to a channel`
- `Publish a message`
- `Quit`

**Comment by mattheworiordan** [comment]
FYI, from the user experiencing this problem:

> I can send you my source code if you want. It's basically two small-ish methods: the first is called when Tomcat instantiates the servlet, the second when Tomcat shuts the servlet down.
> There are 8 test cases, the combination of 3 conditions:
> 1. is network up when servlet instantiated
> 2 is network up when servlet shutdown
> 3. was an Ably connection established

I will be in touch once we have code to reproduce this.

**Comment by mattheworiordan** [comment]
@paddybyers any idea if this is still an issue?

**Comment by paddybyers** [comment]
Resolved by https://github.com/ably/ably-java/pull/404
