### ISSUE TITLE
`ChannelOptions` encrypt / decrypt cipher does not get re-created if `cipherParams` changes later on that channel options instance

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#745]
This is something I've noticed while working on https://github.com/ably/ably-java/issues/741.

As part of the fix for _that_ issue I am writing an `@apiNote` on my new `getEncryptingCipher` and `getDecryptingCipher` methods on `ChannelOptions`, which will reference _this_ issue.

┆Issue is synchronized with this [Jira Bug](https://ably.atlassian.net/browse/SDK-1526) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Perhaps related, I wonder what the `encrypted` boolean field is _also_ doing being present on channel options instances. Surely we would always expect this to be `false` if `cipherParams` is `null`, otherwise we would expect it to be `true`. 🤔

**Comment by ttypic** [comment]
Fixed in https://github.com/ably/ably-java/pull/969/files `ChannelOptions` no longer holds Cipher instance
