### ISSUE TITLE
Use `AutoCloseable` and try-with-resources to clean up `CBCCipher` concurrent modification check

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#747]
This requires us to increase our Android API level requirement from 16 to 19, as that's a requirement of using [AutoCloseable](https://developer.android.com/reference/java/lang/AutoCloseable)

* which then opens us up for using [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html).

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/SDK-1527) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Unblocked by #804.

**Comment by QuintinWillison** [comment]
Oops, sorry for the noise. Wrong issue.

**Comment by ttypic** [comment]
We allowed concurrent  encryption  / decryption in https://github.com/ably/ably-java/pull/969
