### ISSUE TITLE
RTP5c is still implemented in Java code 

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-java#760]
There is a spec about some presence rules when channel becomes attached below
https://docs.ably.io/client-lib-development-guide/versions/v1.0/features/#RTP5c

However this doesn't exist on later versions of feature specs
https://docs.ably.io/client-lib-development-guide/features/#RTP5

This still exists in Java, discovered from comments here
https://github.com/ably/ably-java/blob/85ef987bee729c3d7ba932e621a6b4d4aa84211c/lib/src/main/java/io/ably/lib/realtime/Presence.java#L266

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1805) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@ikbalkaya it turns out that this spec was renamed in newer versions and is still required, thus, I'll close this ticket :wink:
