### ISSUE TITLE
Update dependency: com.google.firebase:firebase-messaging

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-java#774]
We use version `22.0.0` and the newest at the moment is `23.0.4`

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1867) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
@AndyNicks @QuintinWillison this change forces us to also bump the `minSdkVersion` from `16` to `19` for the `ably-android`. This will mean that anyone who uses our library has to also set the minimum supported Android OS version to at least 19 (KitKat). 
Below is a chart that displays the market share of different OS versions. IMO it is safe to bump to version `19` as we will be missing only 0.6% of all devices. Are we okay to do that? WDYT?
![Screenshot from 2022-05-18 13-24-36](https://user-images.githubusercontent.com/62378170/169028018-946a922b-0138-4d55-9acb-c3fffeb5a4c7.png)

**Comment by AndyNicks** [comment]
I agree
