### ISSUE TITLE
Update dependency: org.java-websocket:Java-WebSocket

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-java#776]
We use version `1.4.0` and the newest one is `1.5.3`

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1872) by [Unito](https://www.unito.io)

**Comment by KacperKluka** [comment]
This should resolve https://github.com/ably/ably-java/issues/731

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-1872
