### ISSUE TITLE
Update dependency: Gradle and Gradle Android plugin com.android.tools.build:gradle

### ISSUE THREAD

**Issue by KacperKluka** [ably/ably-java#778]
We use Gradle Android plugin in version `4.1.0` and the newest one is `7.2` (looks scary but they changed versioning from `4.x` to `7.x`, probably to match supported gradle version)

After upgrading the Android plugin we will be able to [upgrade Gradle](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) to version `7.3+`, but we might as well try to use [the newest version](https://gradle.org/releases/) `7.4.2`

Edit:
Even though the newest version is `7.2` we cannot use it as it requires a newer version of the Android plugin. According to [this answer](https://youtrack.jetbrains.com/issue/IDEA-288735/This-version-of-the-Android-Support-plugin-for-IntelliJ-IDEA-or-#focus=Comments-27-5959823.0-0) and [this versions compatibility info](https://developer.android.com/studio/releases#agp-studio-compatibility), we can use version `7.0` at most.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-1870) by [Unito](https://www.unito.io)

**Comment by qsdigor** [comment]
@KacperKluka Hi, why can't you use Gradle version 7.2 or later? Do you have Android Studio Bumblebee or Chipmunk?
 Android plugin is bundled with android studio and should work with newer Gradle versions?

**Comment by KacperKluka** [comment]
Since it's a repository that contains both Java and Android libraries I'd like to make it compatible with both `AndroidStudio` and `IntelliJ`. Currently, the IntelliJ has the Android plugin in version `2020.3.1` which [according to this site](https://developer.android.com/studio/releases#agp-studio-compatibility) supports Gradle `7.0` at most :wink:
