### ISSUE TITLE
Increase emulation test coverage to include our minimum supported Android API Level

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#809]
Currently we only test API Level 24.

I think we now need a matrix, still including 24, but adding 19 ([our new minimum](https://github.com/ably/ably-java/pull/804)) and the current latest level.

I would suggest branching off the branch underlying https://github.com/ably/ably-java/pull/807 to get this work started, which will allow it to support us in testing https://github.com/ably/ably-java/pull/808.

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2081) by [Unito](https://www.unito.io)

**Comment by qsdigor** [comment]
Added exclusion for test for API 19 which does not support PATCH over HttpURLConnection. Other tests pass successfully.
