### ISSUE TITLE
Remove unused HexDump file

### ISSUE THREAD

**Issue by gokhanbarisaker** [ably/ably-java#81]
https://github.com/ably/ably-java/blob/d668973bbd89b5ca5ef836937ef7d32fce5a9aab/lib/src/main/java/io/ably/lib/util/HexDump.java

**Comment by gokhanbarisaker** [comment]
As an alternative, this can be used during debugging http://stackoverflow.com/a/21992128/892500

**Comment by paddybyers** [comment]
Yes, lets remove it.

**Comment by mattheworiordan** [comment]
@trenouf can you remove if it's still included?

**Comment by trenouf** [comment]
Just doing it now.

**Comment by trenouf** [comment]
Fixed by merged PR https://github.com/ably/ably-java/pull/181
