### ISSUE TITLE
Create Feature Compliance Manifest for `ably-java`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/ably-java#817]
For motivation, see [Future Direction for the SDK Manifests](https://github.com/ably/features#future-direction-for-the-sdk-manifests).

In the special case of this particular SDK repository, the manifest has already been populated in the `ably/features`-based prototype: https://github.com/ably/features/blob/main/sdk-manifests/ably-java.yaml

**Comment by QuintinWillison** [comment]
To explain my addition of a suffix to this issue's title, despite its superfluous nature given the GitHub context, it helps us internally when viewing this issue under the Jira epic that it's [sync'd to](https://github.com/ably/engineering/blob/main/sdk/github.md#jira) internally. Sorry.

**Comment by QuintinWillison** [comment]
Internal Jira task: https://ably.atlassian.net/browse/SDK-2412

**Comment by qsdigor** [comment]
We can close this task as this work is already done in the feature repo where all the features are implemented.
