### ISSUE TITLE
Explicitly define charset with String.getBytes()

### ISSUE THREAD

**Issue by gokhanbarisaker** [ably/ably-java#82]

**Comment by mattheworiordan** [comment]
What do you mean?

**Comment by paddybyers** [comment]
> What do you mean?

Use of [getBytes()](https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#getBytes()) is discouraged because it theoretically creates a dependency on the platform's default charset, so it is better to explicitly pass the charset.

**Comment by mattheworiordan** [comment]
@paddybyers should I close this issue then?

**Comment by paddybyers** [comment]
> should I close this issue then?

I assume it was raised because there are still occurrences that don't specify the charset, so leave it open until I or @gokhanbarisaker check

**Comment by mattheworiordan** [comment]
@paddybyers @trenouf can we close this?

**Comment by trenouf** [comment]
@mattheworiordan  I see 5 occurrences of getBytes(). One is in HexDump.java and one in Base64Coder.java, so I think they're ok. The others, in Http.java Auth.java, ProtocolSerializer.java need checking out.

**Comment by paddybyers** [comment]
This is resolved.
