### ISSUE TITLE
[ably-java] Implement no-connection-serial

### ISSUE THREAD

**Issue by jamienewcomb** [ably/ably-java#833]
Implement the changes listed in https://github.com/ably/docs/pull/1526
Reference impl ~~> https://github.com/ably/ably~~js/pull/1045

**Comment by deanna-lad** [comment]
The corresponding Jira issue is https://ably.atlassian.net/browse/SDK-2634

**Comment by sacOO7** [comment]
Going through the relevant PR's and code.
