### ISSUE TITLE
Channel state should be initialized not initialised for consistency

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#85]
Given most of our libraries use `initialized` (see https://github.com/ably/ably-js/blob/d9f706111ec05a981f24be370bd98a6fd406f973/common/lib/client/realtimechannel.js#L13 and https://github.com/ably/ably-ruby/blob/0ba64081f1ee5117f3dafbb6e9fa59e026f471dc/lib/ably/realtime/connection/connection_state_machine.rb#L10) as opposed to `initialised`, and the Java lib even uses [`initialized` for connection state](https://github.com/ably/ably-java/blob/d668973bbd89b5ca5ef836937ef7d32fce5a9aab/lib/src/main/java/io/ably/lib/realtime/ConnectionState.java#L7), I think we should for consistency simply change Channel state to initialized.

We need to update the docs when this is done as it is now being updated to `initialised` for Channels

@paddybyers FYI

**Comment by paddybyers** [comment]
Grudgingly ok

**Comment by tcard** [comment]
On the other hand, there's `Auth#authorise`. Maybe they can be aliased?

**Comment by mattheworiordan** [comment]
> On the other hand, there's Auth#authorise. Maybe they can be aliased?

I know `initialized` is inconsistent, we intended initially on using UK English spellings. I think an alias may in fact cause more confusion as people may not understand why there is an `authorise` and `authorize` function and if they differ.
