### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by PhalugunaRao** [ably/ably-java#850]
### Could not resolve all files for configuration
':app:developmentDebugRuntimeClasspath'.
   > Could not resolve io.azam.ulidj:ulidj:[1.0,2.0).
     Required by:
         project :app > io.ably:ably-android:1.2.2
      > Failed to list versions for io.azam.ulidj:ulidj.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/io/azam/ulidj/ulidj/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/io/azam/ulidj/ulidj/maven-metadata.xml'.
               > Read timed out

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4481) by [Unito](https://www.unito.io)

**Comment by qsdigor** [comment]
I do not see the usage of `io.azam.ulidj:ulidj` library in java SDK. I will look further.

**Comment by ttypic** [comment]
Hey @PhalugunaRao,

Just wanted to check in on this issue since there hasn't been any activity for a while. We're closing it since there's been no recent discussion.

If you still feel this needs attention or have any updates, please reopen it, and we can keep the conversation going!
