### ISSUE TITLE
presence.enter fails on reconnection

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-java#884]
For more context and logs : https://github.com/ably/ably-asset-tracking-android/issues/863

According to above issue, `presence.enter` fails when a new connection is established. A probable cause is treating the non-fatal error (on new connection) as fatal error (@lmars pointed out this).

Todos 

- [ ]  Check existing tests that tests presence behaviour on a reconnection and confirm the issue. 
- [ ]  If a test does not exist, write one, confirm and fix.
- [ ]  If the test exists and this is not an issue -  look for other pointers

**Comment by ikbalkaya** [comment]
I wasn't able to simulate this on test so I'm going to unassign this from myself 
I will look into https://github.com/ably/ably-java/issues/885

**Comment by jaley** [comment]
@ikbalkaya - are you able to check in your reproduction code to a branch so that we can review it and ensure the suspected problem is tested for?

**Comment by ikbalkaya** [comment]
@lmars @jaley Sorry I didn't mean that I couldn't reproduce. I meant I couldn't simulate it with tests. (I couldn't find a way to intercept transport to create conditions for me etc) but I'm pretty sure the issue is there. I wanted to switch to attach/detach issue as I thought this is a possible underlying problem that I could debug easier.

**Comment by jaley** [comment]
Right, understood, thanks. The system test that I've been working on for AAT might help, but one thing I'm unsure of is what the fallback behaviour is when you specify a Realtime host in `ClientOptions`. From my testing so far, it seems like `ably-java` keeps on retrying with that same host, as if it overrides the configured fallbacks, but I could be mistaken. Maybe I just haven't left it long enough? WDYT @lmars ?

**Comment by jaley** [comment]
Just had an offline discussion with @paddybyers -- this limitation with the proxy approach is indeed correct, setting a `realtimeHost` will prevent fallbacks being used. However, we have another equivalent test case planned, whereby we simulate a failed resume, so we can plan for this to be reproduced/covered by the networking connectivity test in AAT. For now, it probably does make sense for you to look at another ticket @ikbalkaya

**Comment by ikbalkaya** [comment]
I think that https://github.com/ably/ably-java/pull/906 might have fixed this issue. To be confirmed

**Comment by deanna-lad** [comment]
Fixed by #906
