### ISSUE TITLE
Re-attach fails due to previous detach request

### ISSUE THREAD

**Issue by ikbalkaya** [ably/ably-java#885]
Context : https://github.com/ably/ably-asset-tracking-android/issues/863

According to issue above, there can be a case where a DETACH is acknowledged after another ATTACH request is sent which leads the ATTACH to fail and channel go into suspended.

Todos 
* Check if there are existing tests for the spec points @paddybyers posted here https://github.com/ably/ably-asset-tracking-android/issues/863#issuecomment-1370191834 . Modify and create new tests to confirm the issue.

**Comment by ikbalkaya** [comment]
@paddybyers I am a bit confused about timers used during attach/detach or reattach operations.
For example `attachTimer` is scheduled here
https://github.com/ably/ably-java/blob/f9e491999b194a6ad250c003ce1202e56eede080/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L419
And also `attachTimer` is scheduled here on detach
https://github.com/ably/ably-java/blob/f9e491999b194a6ad250c003ce1202e56eede080/lib/src/main/java/io/ably/lib/realtime/ChannelBase.java#L517

Can you provide some context on why this timers are used please? Thanks

**Comment by paddybyers** [comment]
See https://sdk.ably.com/builds/ably/specification/main/features/#RTL4f

> Once an `ATTACH` ProtocolMessage is sent, if an `ATTACHED` ProtocolMessage is not received within the [default realtime request timeout](https://sdk.ably.com/builds/ably/specification/main/features/#defaults), the attach request should be treated as though it has failed and the channel should transition to the `SUSPENDED` state. The channel will then be subsequently automatically re-attached as described in [RTL13](https://sdk.ably.com/builds/ably/specification/main/features/#RTL13)

The timer is used to implement this requirement

**Comment by ikbalkaya** [comment]
This is fixed : https://github.com/ably/ably-java/pull/887
