### ISSUE TITLE
Lower case PresenceMessage.Action enum

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#90]
If you look at [ConnectionState](https://github.com/ably/ably-java/blob/master/lib/src/main/java/io/ably/lib/realtime/ConnectionState.java#L6-L15), the enums are all lowercase allowing something like:

```java
switch (state) {
  case connected:
  case failed:
}
```

and the following:

```java
connection.on(ConnectionState.connected, listener) { ... }
```

Same applies for [ChannelState](https://github.com/ably/ably-java/blob/master/lib/src/main/java/io/ably/lib/realtime/ChannelState.java#L6-L13).

However, [`PresenceMessage.Action`](https://github.com/ably/ably-java/blob/master/lib/src/main/java/io/ably/lib/types/PresenceMessage.java#L28-L37) uses upper case making the API interface for devs consistent.  For example, a user will now need to do the following (once https://github.com/ably/ably-java/issues/21 is resolved):

```java
presence.subscribe(PresenceMessage.Action.ENTER, listener) { ... }
``` 

and

```java
switch (action) {
  case ENTER:
  case LEAVE:
}
```

I believe we should aim for consistency in these public enums and should probably just go lowercase. 

WDYT @paddybyers?

**Comment by paddybyers** [comment]
> WDYT

I don't feel strongly about it. The enum values are constants so the usual Java naming convention is that they're upper case, but it's a breakable rule I think. Internal consistency in the java lib has to have a higher priority, and consistency with other libs is also a consideration, although not an overriding priority.

I'm ok for them to change to lower case.

**Comment by mattheworiordan** [comment]
Ok, thanks, lets change to lower then
