### ISSUE TITLE
Message & PresenceMessage Listeners provide arrays of messages, unlike the IDL

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#91]
In our "current IDL":http://docs.ably.io/client-lib-development-guide/features/#idl, message and presence message listeners typically produce one message at a time to the listener. It's not a big issue, but why does Java potentially call the listener with multiple messages instead of just one like all other libs?

@paddybyers?

**Comment by mattheworiordan** [comment]
@paddybyers any thoughts on this as we're doing an API clean up now?

**Comment by paddybyers** [comment]
The original idea was that the listeners took an array, so if multiple messages happen to be deliverable simultaneously, then that was possible only calling each listener once.

Now we're delivering each message separately there's no point in having an array of messages passed to the listener. It's a trivial change so we should go ahead and do it.

**Comment by mattheworiordan** [comment]
Ok, @gokhanbarisaker please go ahead and make this change.  I will add it to the prioritisation sheet

**Comment by gokhanbarisaker** [comment]
Should I also make the same change for `ProtocolMessage`'s `Message` array variable?

https://github.com/ably/ably-java/blob/603d78813054ad564d6e1ea8ef5e81e56a490d03/lib/src/main/java/io/ably/lib/types/ProtocolMessage.java#L116

**Comment by paddybyers** [comment]
> Should I also make the same change for ProtocolMessage's Message array variable?

You mean change it to be just a `Message`, not `Message[]` ?

No. A `ProtocolMessage` may contain multiple messages. The reason for this issue is that, when that occurs, then `Message`s are still delivered to the listener singly.

**Comment by gokhanbarisaker** [comment]
@paddybyers thanks. Then, current pull request #106 should solve the problem.
