### ISSUE TITLE
Reauthentication on external URLs 

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-java#92]
Looking at https://github.com/ably/ably-java/blob/8a151b4edfa228ddef806fa10d2f9ce2be1ac09c/lib/src/main/java/io/ably/lib/rest/Auth.java#L379, one can see that `authUrl` requests use the ably HTTP library to get the authentication token when `authUrl` is provided.

However, this is designed incorrectly as far as I can see because:

* [authUri calls httpExecute](https://github.com/ably/ably-java/blob/8a151b4edfa228ddef806fa10d2f9ce2be1ac09c/lib/src/main/java/io/ably/lib/http/Http.java#L137)
* [httpExecute tries to reauthenticate 401 errors](https://github.com/ably/ably-java/blob/8a151b4edfa228ddef806fa10d2f9ce2be1ac09c/lib/src/main/java/io/ably/lib/http/Http.java#L335-L346), which means an external 401 failure will trigger a local reauth unnecessarily
* [We are returning Ably wrapped exceptions](https://github.com/ably/ably-java/blob/8a151b4edfa228ddef806fa10d2f9ce2be1ac09c/lib/src/main/java/io/ably/lib/http/Http.java#L352) instead of raw HTTP exceptions for external URLs.

To me, it makes more sense to have a:

* httpExecute method that simply executes HTTP requests, wraps them in generic exceptions or even raw Java HTTP exceptions, and returns the result.  It will never interfere with the response or try and remedy the issue
* Then have a set of Ably requests i.e. get, post, del that are named ablyGet, ablyPost, ablyDel and they in turn call [ablyHttpExecute](https://github.com/gokhanbarisaker/ably-java/blob/RSC15/lib/src/main/java/io/ably/lib/http/Http.java#L264) which is the only method responsible for altering the response, trying fallbacks, re-authenticating etc.

@paddybyers WDYT?

@gokhanbarisaker FYI, any thoughts appreciated

**Comment by paddybyers** [comment]
> httpExecute method that simply executes HTTP requests, wraps them in generic exceptions or even raw Java HTTP exceptions, and returns the result

If the exceptions from authURL requests were being thrown directly back to user code to handle then I'd agree that they should be the raw exception. However, it's the library's job to deal with the aftermath and so, once any type-specific processing has been done, I think it is fine then for them to be wrapped in a type that allows them to be handled uniformly from that point on. We can always return the `cause` in error messages or callbacks that ultimately reach the client.

> It will never interfere with the response or try and remedy the issue

Agreed.

> Then have a set of Ably requests i.e. get, post, del that are named ablyGet, ablyPost, ablyDel and they in turn call ablyHttpExecute which is the only method responsible for altering the response, trying fallbacks, re-authenticating etc.

This was the intended approach of course but the re-auth in `httpExecute()` is in the wrong place.

**Comment by mattheworiordan** [comment]
> If the exceptions from authURL requests were being thrown directly back to user code to handle then I'd agree that they should be the raw exception. However, it's the library's job to deal with the aftermath and so, once any type-specific processing has been done, I think it is fine then for them to be wrapped in a type that allows them to be handled uniformly from that point on.

Agreed

> We can always return the cause in error messages or callbacks that ultimately reach the client.

Yes, well that is what I was alluding to, we should be passing a suitable error to the ConnectionStateChange and in the ErrorInfo

> This was the intended approach of course but the re-auth in httpExecute() is in the wrong place.

Ok, so we should move it into ablyHttpExecute then, changing this issue to a bug

**Comment by mattheworiordan** [comment]
I believe this is may be an issue for potentially retrying requests for external URLs as well, see https://github.com/ably/ably-java/pull/80/files#diff-a93f75fd1c92d5797fcc98928286df75R102 which implies that it's retrying any request using the `httpExecute` method.
