### ISSUE TITLE
`AblyRest.request` may not be using retries or fallbacks

### ISSUE THREAD

**Issue by jaley** [ably/ably-java#953]
I can't be 100% convinced, but I was trying to confirm that `AblyRequest.request()` will perform retries and make use of fallbacks when needed through code inspection. I've followed the code as best as I can and can't see any evidence that it does actually do this. 

It looks to me like calling `AblyRest.request()` will [create an HttpPaginatedRequest directly](https://github.com/ably/ably-java/blob/main/lib/src/main/java/io/ably/lib/http/HttpPaginatedQuery.java#L49) and just call exec() on that, which schedules a runnable to execute the request and waits on it synchronously. If the request fails, an exception is thrown. I can see that other APIs are using a wrapper to retry with fallbacks, but it seems that doesn’t happen for raw requests made this way.

Might be good if someone with more experience of the codebase could review and confirm, as this seems like a bug.

**Comment by AndyTWF** [comment]
Hi @jaley - we've discussed this internally so I'll close this now, but for the benefit of others seeing this:


`AblyRest.request()` does use fallback hosts. The call to exec here https://github.com/ably/ably-java/blob/c3f438a8b1992850f68a16f9e7517a5dc205727e/lib/src/main/java/io/ably/lib/http/HttpPaginatedQuery.java#L54 ends up calling the fallback host logic. :)
